### ISSUE TITLE
Maps - issues with 3 or more layers

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#103]
When a map has 3 or more layers, there is a problem with the nested zooming. The visibility of the layers appears to be messed up until the map has been fully zoomed in and the fully zoomed out.

**Comment by Norric1Admin** [comment]
@brockfanning 
I've set the map to display [two boundaries](https://github.com/ONSdigital/sdg-indicators/commit/725026059e40f16edc2c81d73bfe942091a7139e) (Country and Region) and this works correctly, except that the England 'Country' boundary only shows once the user zooms in a step, then back out. The confusion seems to be caused by the underlying layer, and which to show first.
http://sdg.mango-solutions.com/data-deploy/3-2-1/

**Comment by Norric1Admin** [comment]
For now, the boundaries Region and LA are displaying. These work well in conjunction.
http://sdg.mango-solutions.com/data-deploy/3-9-1/
http://sdg.mango-solutions.com/data-deploy/3-a-1/
