### ISSUE TITLE
Blog area on open-sdg.org

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1047]

**Comment by brockfanning** [comment]
@AnnCorp I'm noticing that the typical Jekyll content type for blogs, called "posts", is actually what we already have under "News" on the site. I just wanted make sure that we need to have a distinction between "News" and "Blog". I guess the options are:

1. Separate "News" from "Blog" with different menu items and different landing pages
2. Combine them both under "News"
3. Combine them both under "Blog" (ie, change the current "News" menu item to "Blog")

Thoughts?

**Comment by AnnCorp** [comment]
@brockfanning my initial thought is to have separate as could be very different styles (news could be quite short and factual compared with a blog style) and not all Blogs would be News eg might we do a blog at some point on how Open SDG came about or sharing findings from user research, share our design principles etc. @LucyGwilliamAdmin any thoughts?
As an aside, should we need to commit to doing a News entry for each release, more to highlight and link to detailed release information, rather than reproduce it.
