### ISSUE TITLE
Remove Github links from the data/metadata last-updated fields

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1051]
Usability testing October 2020 in the UK discovered that dates displayed in the national metadata ("Data last updated" and "Metadata last updated") were difficult to interpret because of the date format used (e.g. YYYY-XX-XX) it was unclear to those in the UK which is month and which is day

Recommendation:
Use the format DD-MM-YYYY for all dates displayed in the UK.

**Comment by phillipgardiner** [comment]
@AnnCorp further research has discovered that the date format currently used matches the international standard: https://www.w3.org/QA/Tips/iso-date. If so this issue may only relate to the UK.

**Comment by AnnCorp** [comment]
@phillipgardiner thanks for the update. 
@brockfanning @LucyGwilliamAdmin any thoughts on could we build some configuration option into Open SDG that would allow control of how date format appears please?

**Comment by brockfanning** [comment]
@phillipgardiner This is specifically about "Data last updated" and "Metadata last updated", correct?

Those two fields, which are automatically populated, are problematic in another way too: they aren't being translated into other languages.

**Comment by phillipgardiner** [comment]
@brockfanning Yes that is correct

**Comment by brockfanning** [comment]
@phillipgardiner @AnnCorp @LucyGwilliamAdmin @jwestw 
Ok, given that those two fields are also problematic in not being translated, I'd suggest we first consider some changes to those two fields.

Right now, the actual metadata in those fields contains that full text, eg "2021-01-01: see changes on Github" (as you can see happening [here](https://github.com/open-sdg/sdg-build/blob/master/sdg/inputs/InputMetaFiles.py#L77)). By combining the date and text like this, we are making it difficult for ourselves in two ways:

* It's difficult to control the date format
* It's difficult to translate the text

My suggestion is that we change those fields to _only_ have the date, eg "2021-01-01". By having the date isolated like this, we will be able to more easily convert it into different date formats, using our existing [date_formats site configuration](https://open-sdg.readthedocs.io/en/latest/configuration/#date_formats).

If we want to retain that "see changes on Github" functionality, we would need to add 2 additional fields called (something like) "How data changed" and "How metadata changed". So that section of metadata would be something like this 4-field approach (showing dates formatted in DD-MM-YYYY):

|||
|---|---|
|**Data last updated**|07-01-2021|
|**How data changed**|[See change on Github](https://github.com/ONSdigital/sdg-data/commit/7c647f95890af8cbc6087c386e71e211a1e2dcd3)|
|**Metadata last updated**|07-01-2021|
|**How metadata changed**|[See change on Github](https://github.com/ONSdigital/sdg-data/commit/7c647f95890af8cbc6087c386e71e211a1e2dcd3)|

As opposed to the current 2-field approach:

<img width="335" alt="update-dates" src="https://user-images.githubusercontent.com/1319083/104322330-d6d30e80-54b2-11eb-820c-44a645cbdffd.png">

**Comment by AnnCorp** [comment]
@brockfanning embracing our 'simple' design aspiration I think the 4 field approach is better. 
@LucyGwilliamAdmin @jwestw @phillipgardiner what are your thoughts on this one please?

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin @AnnCorp @jwestw Yep totally agree with splitting out the date to make things easier. My main question would be 'see changes on Github' - what is the purpose of this? Is it even required? I know its always been there but what is the user need around it / is there one?

**Comment by AnnCorp** [comment]
@phillipgardiner I think it originated as a quick way for showing what had changes, but its a bit techie. @LucyGwilliamAdmin @jwestw is there a quick way of finding out numbers for clicking through these links?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp I've just checked and unfortunately Google Analytics doesn't provide data on clicking of links by default - my thoughts generally are that I think those fields would be much more useful if they actually said what the change is. I think the most use from this would be whether a change is an actual change or just a typo fix for example

**Comment by phillipgardiner** [comment]
@AnnCorp @LucyGwilliamAdmin I guess i'm also thinking what type of user this is targeted at?

We have time to consider option,s by currently i'm thinking:
1) Remove the 'How data changed all together'
2) Use brocks approach of separation across lines
3) Only display dates, but these could be links through to the Github info

However we shouldn't keep the links / see changes in Github if there isn't really any user need.

**Comment by AnnCorp** [comment]
So lets go with removing git hub links then, just keep dates and then in UK we can configure the date to the format we need.

**Comment by jwestw** [comment]
I also noted a while ago that the link to github wasn't very useful as (if I remember correctly) it didn't actually link back to the data in question and therefore was a bit confusing. I would totally agree with removing the github links.

**Comment by brockfanning** [comment]
Ensure that the date format can be configured.
