### ISSUE TITLE
Mapping: Year slider should skip years with no data

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/open-sdg#107]
Can we omit years in the year slider if they don’t appear in the CSV? The geojson does recognise gaps, and they are coded into [jquery.sdgMap.js](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/jquery.sdgMap.js) under ‘record.Year’ or ‘currentYear’ I think. We need a way for the year slider to ignore these, as it currently shows multiple years with no data.

Example: https://sustainabledevelopment-rwanda.github.io/sdg-indicators/1-2-1/

**Comment by brockfanning** [comment]
This should be possible. I'm thinking we'll need to use the ["times" option](https://github.com/socib/Leaflet.TimeDimension#options) to specify an array of specific times, instead of using ["timeInterval"](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/leaflet.yearSlider.js#L43) and ["period"](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/leaflet.yearSlider.js#L42) like we are now.

**Comment by Norric1Admin** [comment]
Brilliant - could this be made to read the valid years from the CSV (record.Year)?

**Comment by brockfanning** [comment]
Yes, it turned out to be fairly easy. I've got a PR up: #119
