### ISSUE TITLE
Cookie enable/disable functionality

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1231]
In order to meet data protection regulations, we need to give end users the option to to enable and disable cookies, with them being disabled by default.

Requirements:

Need to give option for out of box cookies -  cookies that remember your settings e.g. contrast state and for cookies that measure website use e.g. google analytics.

However countries should be able to configure what cookies they want to provide the option for e.g. if they start using another analytical software or customise the platform so there's another cookies that remembers settings.

Banner text should be customisable

Cookie journey:
[Cookie_Consent.pdf](https://github.com/open-sdg/open-sdg/files/6638166/Cookie_Consent.pdf)

Include documentation

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning not sure if you're already aware of this but just came across this info on how to disable google analytics tracking: https://docs.publishing.service.gov.uk/manual/cookie-consent-on-govuk.html#google-analytics

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @phillipgardiner This (cookie consent) is one area where there are a ton of third-party libraries out there. Many of them appear to be for-profit companies trying to sell their services, but some also offer an open-source "community edition". One of the most feature-rich and open-source-friendly library I've found so far is [Klaro](https://heyklaro.com/docs/). Klaro also lines up pretty nicely to the journey described in the PDF here.

So I'm inclined to try to use Klaro for this, to support our design principle of trying to use open-source libraries, and avoiding custom code when possible. That raises a few questions:

1. To what degree should we try to exactly match the mockup? For example, out of the box Klaro displays everything in a modal popup (screenshots below). I think it would probably be possible to customize the Klaro configuration to get closer to the mockup, but I don't want to introduce extra work if it's not needed.
2. An important aspect of this is adding the initial text to the sdg-translations repository so that it can be translated. So we will need to decide on the exact text ASAP. We should make sure to keep in mind that the starting language should be general enough to be useful to the majority of use-cases (ie countries/cities/etc). Each particular country/city/etc can customize the language, but we need somewhere to start.
3. We'll want to take stock of the features of Open SDG that may introduce cookies, and then have the initial Klaro configuration set up to handle these cookies. As far as I know, they consist of:

    * High-contrast mode
    * Google Analytics
    * ShareThis
  
    Are there any others I've forgotten?
  

Here are some screenshots of the Klaro interface. **Note that all the labels/text/buttons/colors can be changed pretty easily.**


**First you get the initial popup:**

![screenshot-127 0 0 1_4000-2021 06 14-10_58_26](https://user-images.githubusercontent.com/1319083/121913565-81b85480-ccff-11eb-985b-f1ac99d321e6.png)


**Then if you click "Let me choose", you see a bigger popup which groups the cookies/services according to "purpose":**


![screenshot-127 0 0 1_4000-2021 06 14-11_00_19](https://user-images.githubusercontent.com/1319083/121913958-d52aa280-ccff-11eb-9dd5-65c714f20ef2.png)


**Whenever you accept/deny/save the settings, the popup just goes away and there is no other message. I've also added a "Cookie settings" link in the footer that brings the bigger popup back:**


![screenshot-127 0 0 1_4000-2021 06 14-11_03_44](https://user-images.githubusercontent.com/1319083/121914400-38b4d000-cd00-11eb-823e-c29e53ee4543.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Re. 3 it seems we're also using a Cloudflare cookie in UK - is that an Open SDG thing?

@phillipgardiner are able to provide answers on 1 and 2?

**Comment by brockfanning** [comment]
I'll try to come up with some general text for the Sharethis cookie, to get us started with that. @LucyGwilliamAdmin I'm not seeing the Cloudflare cookie.

@phillipgardiner To get a bit more specific here are a few examples of things we would need to decide, if we decide to go with Klaro:

1. The Klaro library doesn't display any message *after* the user selects an option - it just disappears. So that aspect of the mockup is not supported out of the box. I think it might be possible to add some code that does a separate popup after a choice is made, if we decide that that part is important enough.
2. As you can see in the screenshots, the default language for the buttons in the initial popup are "That's OK" and "I decline". The mockup uses "Accept analytics cookies" and "Reject analytics cookies". One issue with the mockup's buttons is that a site might use more than just analytics cookies. For example if a site is using Sharethis cookies then "analytics" wouldn't really apply.
3. The Klaro library doesn't show a heading on the popup. In the mockup there is the heading "Cookies on [name of service]". We might be able to add this with custom code, if we decide it's important enough.

There's more I'm sure but those are meant to show some of the considerations in deciding whether to use this third-party library Klaro and the differences from the mockup.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning there used to be one so did some research - looks like it's been deprecated so don't need to worry about that:
https://blog.cloudflare.com/deprecating-cfduid-cookie/

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin wow lots to feed back on so here goes.....ultimately I think we need to get @AnnCorp involved in this conversation. The mock up that I created is based on the GDS best practices and supported by user research. To be honest I am not sure if even if we wanted to we could move away from the proposed journey and design due to in the UK having the requirement of passing GDS assessments (but this is not necessarily a requirement for all other countries)

_1) To what degree should we try to exactly match the mockup? For example, out of the box Klaro displays everything in a modal popup (screenshots below). I think it would probably be possible to customize the Klaro configuration to get closer to the mockup, but I don't want to introduce extra work if it's not needed._

For me the answer would be 'exactly'. This however is largely based on what I mentioned above about assessments etc. Doing something different to this may be acceptable if this is not a factor, but in that instance we would require significantly more  usability testing etc to ensure the output is usable. I also wonder are the Klaro 'pop-up's (small and large) compatible with our accessibility requirements (e.g. AA)? 

_2) An important aspect of this is adding the initial text to the sdg-translations repository so that it can be translated. So we will need to decide on the exact text ASAP. We should make sure to keep in mind that the starting language should be general enough to be useful to the majority of use-cases (ie countries/cities/etc). Each particular country/city/etc can customize the language, but we need somewhere to start._

Assuming we go with the GDS patterns. The different scenarios of wording required are listed within their document, so we would use this as the basis (https://design-system.service.gov.uk/components/cookie-banner/). I've also updated the cookie journey to reflect recent changes to our cookie policy wording (
[Cookie Consent.pdf](https://github.com/open-sdg/open-sdg/files/6656093/Cookie.Consent.pdf). @brock I noticed you spotted this to (e.g. was 'analytics' now 'additional' - as we have more than just analytics cookies).

_3) We'll want to take stock of the features of Open SDG that may introduce cookies, and then have the initial Klaro configuration set up to handle these cookies. As far as I know, they consist of: High-contrast mode, Google Analytics and ShareThis

No others that I'm aware of. @brockfanning what is ShareThis and its function?

_4) The Klaro library doesn't display any message after the user selects an option - it just disappears. So that aspect of the mockup is not supported out of the box. I think it might be possible to add some code that does a separate popup after a choice is made, if we decide that that part is important enough._

I would say this is very important. Putting aside the GDS pattern. Its good UX practice to support users with confirmation of their actions.

_5) As you can see in the screenshots, the default language for the buttons in the initial popup are "That's OK" and "I decline". The mockup uses "Accept analytics cookies" and "Reject analytics cookies". One issue with the mockup's buttons is that a site might use more than just analytics cookies. For example if a site is using Sharethis cookies then "analytics" wouldn't really apply._

As mentioned above (and now shown on the new cookie journey document) this would be supported with the labels: 'Accept additional cookies' and 'Reject additional cookies' 

_6) The Klaro library doesn't show a heading on the popup. In the mockup there is the heading "Cookies on [name of service]". We might be able to add this with custom code, if we decide it's important enough._

Again I would say its important as it supports the user with confirmation to which site the cookie messaging applies. It's also a standard across government within the UK.

Alot of this comes down to potential differences between maybe what is required for the UK and what may be required for all other countries? Within the UK, all government and related sites (e.g. CENSUS, SDG's) aim to follow a similar pattern to minimise the user's memory loads via not having to use lots of different patterns to achieve the same outcome. Following these patterns also means research and any issues are shared across government. 

I think maybe a specific meeting or time at a tech call is required to discuss this is more detail as there are lots of different factors involved (e.g. GDS v non GDS, UK v Worldwide, Development Resource, UX resource etc etc) and pro and cons.

**Comment by brockfanning** [comment]
Great points @phillipgardiner. I agree that a cookie meeting may be called for. :)

In the meantime I'm going to do my own uneducated accessibility audit of Klaro, and also check to see roughly how much work would be involved in getting the various things needed to match the mockup better.

**Comment by AnnCorp** [comment]
All: am on a course and out of circulation until Thurs - perhaps we could have initial discussion on this at Tech call Thurs, depending on any other priorities (will initiate a slack thread re Tech call)

**Comment by LucyGwilliamAdmin** [comment]
Don't want to make things more complicated but it's just occurred to me Google Analytics only works if a country configures it to, so if Google Analytics hasn't been configured, would we only want the other option to show.

Similarly for ShareThis

By the way @phillipgardiner, ShareThis functionality is documented here:
https://open-sdg.readthedocs.io/en/latest/social-media-sharing/#configuring-sticky-share-buttons

It was added quite a while ago and don't think anyone is actually using it. It def hasn't been accessibility tested. Kyrgyzstan requested it originally and it was straightforward to add but they haven't actually started using it, no idea if they are still planning to? Could possibly remove??

**Comment by brockfanning** [comment]
I think we would need the list of services to be configurable, and we could hardcode the Google Analytics and/or Sharethis to be included in the consent form only if they are enabled on the platform.

Another is Google Webfonts - they do not set a cookie, but it does seem like there may be a privacy concern: https://usercentrics.com/knowledge-hub/google-fonts-gdpr-compliant/

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner is there a similar font we can use that doesn't require Google Fonts? Yesterday, when I was testing #1234, originally Google Fonts had been removed and this was the outcome:

![image](https://user-images.githubusercontent.com/43404358/122208753-9df0f880-ce9b-11eb-9dc6-25fa5b67b792.png)

They look very similar with and without Google Fonts, maybe the weight could be reduced?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning sorry I don't know enough about how fonts work (e.g. what makes it a google font verses some other font) I always assumed we followed GDS guidelines? _You should use an alternative typeface like Helvetica or Arial for services that are publicly available on different domains_

**Comment by phillipgardiner** [comment]
> Don't want to make things more complicated but it's just occurred to me Google Analytics only works if a country configures it to, so if Google Analytics hasn't been configured, would we only want the other option to show.
> 
> Similarly for ShareThis, which I completely forgot about.
> 
> By the way @phillipgardiner, ShareThis functionality is documented here:
> https://open-sdg.readthedocs.io/en/latest/social-media-sharing/#configuring-sticky-share-buttons
> 
> It was added quite a while ago and don't think anyone is actually using it. It def hasn't been accessibility tested. Kyrgyzstan requested it originally and it was straightforward to add but they haven't actually started using it, no idea if they are still planning to? Could possibly remove??

I think best to discuss all this at tech call or separate meeting. I may be misunderstanding the requirement (e.g. are we creating the content for the pages for everybody, or are we just providing them with blank pages on which they can add their own content (if and when required). I feel a few things need clearing up before we spend lots more time on this.

**Comment by brockfanning** [comment]
@AnnCorp @phillipgardiner @LucyGwilliamAdmin I've looked more into the possibility of having a confirmation pane with Klaro and it looks like it is possible, since Klaro has a hook which can be used to respond to a variety of events.

However I noticed another UX-related issue: with Klaro the toggle for each service is a checkbox (styled as a sliding on/off toggle).
![screenshot-127 0 0 1_4000-2021 06 17-16_37_58](https://user-images.githubusercontent.com/1319083/122469383-e509e700-cf8a-11eb-8f28-f553314c2c5f.png)

But in the mockup, the toggle is a radio-button.
![cookie-radios](https://user-images.githubusercontent.com/1319083/122469584-1edaed80-cf8b-11eb-91eb-85e4eb9deaaf.png)

I don't think this is flexible, so if it needs to be radio-buttons specifically, then I don't think Klaro will work for the UK.

**Comment by AnnCorp** [comment]
@brockfanning have responded more fully on Slack re parking the Klaro exploration for now please and focussing on buidling a GDS- based solution as per @phillipgardiner 's mockups please.

**Comment by brockfanning** [comment]
In shifting focus to the GDS-based solution I've realized that Klaro serves two distinct purposes: cookie management, and a cookie consent form. And because Klaro's API is available, we can actually use it only for the cookie management piece, and write our own cookie consent form. This might be the best way to incorporate the feature into Open SDG but still have a fully custom consent form per country:

1. Out of the box, Open SDG uses the stock Klaro popup consent forms (if enabled)
2. Countries can override this and create their own consent forms

This saves us from needing to write custom code in this project, and still allows for full customization by countries. We can discuss more as we test the country-approach at https://github.com/ONSdigital/sdg-indicators/issues/3523

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin @AnnCorp Have put the latest documents on our slack conversation. These show the expected cookie journey and a mock up of the cookie page - along with supporting notes and references. These were updated following the decision to classify 'contrast' as an essential cookie therefore removing our need for a 'settings' group.

**Comment by LucyGwilliamAdmin** [comment]
Need to keep an eye on whether countries are adding services as well as cookies
