### ISSUE TITLE
Search results not loading in AWS S3

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1254]
**Please complete the following information** 
Site repository URL: https://github.com/ONSdigital/sdg-indicators]
Open SDG version: 1.4.0-beta1

**Describe the bug**
After entering a search term and clicking search, the results never show - the loading icon just displays indefinitely

**To Reproduce**
1. Go to 'http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-1.4.0-beta1/'
2. Search for 'Smoking' (or anything really)

**Expected behavior**
After searching for a term, relevant search results should show

**Screenshots**
![image](https://user-images.githubusercontent.com/43404358/123658760-ed371180-d829-11eb-9be7-2784e245d5c5.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version: 90

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think this is specific to Amazon S3. I don't know of a quick fix, but there is some discussion here: https://stackoverflow.com/questions/23993675/amazon-s3-redirect-rule-get-data-is-missing

My hope is that there is some setting we can change in S3 that will allow query strings to work.

If we decided to fix this on the Open SDG side (which may be reasonable if we want to make S3 integration easier) then we could change the search feature to use a hash instead of a question mark. Ie, `/search#q=poverty` instead of `/search?q=poverty`. But I would consider it a lower priority since it is specific to S3.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ahh ok - yes low priority since only affects S3 - thanks for pointing that out, I thought it was an Open SDG wide problem. I'll rename this issue slightly.

Also found this discussion which also sounds similar:
https://stackoverflow.com/questions/20751301/how-can-i-get-query-strings-in-my-amazon-s3-static-website

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning so do you know what happens when searching for a term? What is S3 trying to do?
