### ISSUE TITLE
Ensure shapes on tooltips match shapes on chart

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1274]
Currently the shapes shown on the chart tooltips are all square. However, they should match the shape of the corresponding line on the chart i.e. the headline data square should be square and all of the others should be circle:

Current:
![image](https://user-images.githubusercontent.com/43404358/126362068-2d931030-f4f0-4edb-90aa-b5554a45317e.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you know how much time/effort this will take?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This will be a high level of effort. The problem is that the tooltips are generated as Canvas elements, which means that normal CSS rules do not affect them. After some experimentation I think that our options would be:

1. Switching to custom HTML tooltips. With HTML tooltips we would be able to style them with CSS. But this would involve creating and styling brand new elements and then integrating them into Chart.js. I would estimate probably about 20-25 hours of work.
2. Upgrading to the latest version of ChartJS: 3.5.0. In the latest version there is a "usePointStyle" option which should (in theory) handle this automatically. However this is a major version upgrade and it has a lot of breaking changes. So we would need to update most/all of our Chart.js customizations according to their [migration guide](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html). This is tough to estimate without knowing how much of our customizations would need to be updated, but I think it would be at least 20 hours as well. I don't think we should do this until version 2.0.0 of Open SDG though, because it would break backwards-compatibility for anyone use custom Chart.js-related code.

**Comment by LucyGwilliamAdmin** [comment]
To be considered if/when upgrading to next Chart.js

**Comment by brockfanning** [comment]
This will be fixed by #1548

**Comment by LucyGwilliamAdmin** [comment]
Closing as went in to 1.8.0
