### ISSUE TITLE
Units mousover"undefined"

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1313]
If I use units on the chart in mouseover appeeras "undefined: %"
How do I avoid this "undefined" or where can i change it to e.g. "Einheit" ?

![image](https://user-images.githubusercontent.com/67795376/132172424-2b7e86ea-fe5f-4707-824e-4ba463ffd6f7.png)

[my site repository](https://github.com/WohnungNDS/IM_Site)

[my data repository](https://github.com/WohnungNDS/IM_Data)

[example indicator](https://wohnungnds.github.io/IM_Site/4-1-6/)

Thanks a lot!

**Comment by MoBosse** [comment]
It is probably because `unit` doesn`t get translated. If I am not mistaken [this line](https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_includes/assets/js/indicatorView.js#L490) is creating the Unit in the chart tooltip. Could you check if there is a translation key called 'unit' in the folder called 'indicator' where ever your translations come from?

**Comment by WohnungNDS** [comment]
@MoBosse  Great! It works!
I had: 
`unit_of_measurement: Einheit`
`units_type: Einheit`
in my translation indicator.yml
After adding `unit: Einheit` it works....

Thank you!
