### ISSUE TITLE
adding a plural translation for data-footnote

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1316]
Sometimes I have a lot of footnotes, as you can see  [here](https://wohnungnds.github.io/IM_Site/4-1-6/) 

How do I add a translation for plural footnote**s** in German Fußnote / Fußnoten

![image](https://user-images.githubusercontent.com/67795376/132176402-36161a2e-a247-4e0a-b552-92269bf5d7ad.png)

[my site repository](https://github.com/WohnungNDS/IM_Site)

[my data repository](https://github.com/WohnungNDS/IM_Data)

Thanks a lot!

**Comment by brockfanning** [comment]
@WohnungNDS If you are OK with making it plural site-wide, I believe you could try editing your local translations here: https://github.com/WohnungNDS/IM_Data/blob/develop/translations/de/indicator.yml#L21

**Comment by WohnungNDS** [comment]
@brockfanning No, I don't want do make it site-wide plural. After serveral attepmpts to add another field in my _[prose.yml](https://github.com/WohnungNDS/IM_Data/blob/556af2e62e9745c45e47c7127bc71eaea60f5e1e/_prose.yml#L88) I used the field copyright with the translation "Fußnoten". 
At least this works... but its not the gentelmen way ,-)

I am wondering why it doesnot work. I added a data_source field here:  https://github.com/WohnungNDS/IM_Data/blob/556af2e62e9745c45e47c7127bc71eaea60f5e1e/_prose.yml#L210
and added translations here: 
https://github.com/WohnungNDS/IM_Data/blob/556af2e62e9745c45e47c7127bc71eaea60f5e1e/translations/de/metadata_fields.yml#L84

and it works great.... as you can see here: https://wohnungnds.github.io/IM_Site/1-1-1/ (metadata tab: "Datenquellen"

So why it does not work with another field called data_footnotes?

**Comment by MoBosse** [comment]
I think you have to overwrite the data-footer file from open-sdg for this. Could you try to copy [this file](https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_includes/components/indicator/data-footer.html) to your repository and paste one more of [these blocks](https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_includes/components/indicator/data-footer.html#L35-L38) but with "data_footnotes" instead of "data_footnote". Now you should ba able to use both, footnotes aswell as footnote.

**Comment by WohnungNDS** [comment]
@MoBosse it works, great! Thank you!
