### ISSUE TITLE
1.5.0 beta testing: table row/column header font has changed

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1327]
**Please complete the following information** 
Site repository URL: github.com/ONSdigital/sdg-indicator
Open SDG version: 1.5.0-beta1

**Describe the bug**
The font for table row and column headers seems to be a different style to that in v1.4.0

**To Reproduce**
1. Go to http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-1.5.0-beta1/1-2-1/
2. Click 'Select all' under Ages dropdown
3. Click Table tab
4. See error on row headers
5. Also scroll down to metadata tab section
6. See error on column headers

**Expected behavior**
Font should not have changed

**Screenshots**
Feature branch:
![image](https://user-images.githubusercontent.com/43404358/132680488-d0171fd4-fd10-4537-8a8d-9e8f02264b37.png)

Live site:
![image](https://user-images.githubusercontent.com/43404358/132680530-d0ce4b8a-4706-422f-94d8-a0bb415036df.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This appears to have happened because of our switch to self-hosted fonts. In switching over from Google to self-hosted, I had the option of which variations of the font to install. I opted for installing four versions:
* [normal](https://github.com/open-sdg/open-sdg/blob/1.6.0-dev/_sass/font-face.scss#L2-L9)
* [italic](https://github.com/open-sdg/open-sdg/blob/1.6.0-dev/_sass/font-face.scss#L11-L19)
* [bold normal](https://github.com/open-sdg/open-sdg/blob/1.6.0-dev/_sass/font-face.scss#L21-L29)
* [bold italic](https://github.com/open-sdg/open-sdg/blob/1.6.0-dev/_sass/font-face.scss#L31-L39)

Whereas, before when we were using Google, we were using [this font definition](https://fonts.googleapis.com/css?family=Open+Sans|Roboto) which does not include any bold or italics versions. It only has one version, multiple times for a few different alphabets. (Note it also has a few "Roboto" fonts but we were not using those.)

So, in a sense we have improved things, though it does appear to be a change. If needed, we could remove the self-hosted bold and italics versions and I think it would look the same as before.

As I understand it, when a browser does not have a special version of a font for bold, it dynamically alters the font to make it appear bold. And likewise for italics.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think if it's an improvement then probably fine to leave as is. @phillipgardiner what are your thoughts?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Good spot Lucy. Despite it being a change, I think its alright to leave as is.

**Comment by LucyGwilliamAdmin** [comment]
Ok, thanks both - closing issue
