### ISSUE TITLE
Print table, chart or map 

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1414]
**Is your feature request related to a problem? Please describe.**
My clients like printing very well. They want to Print the table, the chart or even the map.
@MoBosse may be your clients like printing everything as well :-)

**Describe the solution that you need**
next to the "download Button I'd like to have a Button for printing the "main content"

I found this js on the web and added it to my [custom.js](https://github.com/WohnungNDS/IM_Site/blob/develop/assets/js/custom.js) file
````
function printDiv() 
{

  var divToPrint=document.getElementById('main-content');

  var newWin=window.open('','Print-Window');

  newWin.document.open();

  newWin.document.write('<html><body onload="window.print()">'+divToPrint.innerHTML+'</body></html>');

  newWin.document.close();

  setTimeout(function(){newWin.close();},10);

}
````
Then I put this line 

`<input type='button' id='btnSave' value='Print' class="btn btn-primary btn-download" onclick='printDiv();'>`

in my [previous_reports.md](https://github.com/WohnungNDS/IM_Site/blob/develop/_pages/previous_reports.md)

and it works great as you can see [here](https://wohnungnds.github.io/IM_Site/previous_reports/)

clicking on the print-button the printing dialoge opens.....

![image](https://user-images.githubusercontent.com/67795376/140277996-3d85b752-6062-47ea-9daa-6b10f8211d89.png)

Two Questions:

1) Where do I put this line to print out the table, chart or map?
2) I am not familiar to .js. It looks like a new window (with the content tp print) will be opened. After printing the window will be closed. It will be more smart to print the div directly. How do I have to change the js file to do this?

**Comment by MoBosse** [comment]
@WohnungNDS in fact I am just thinking about a similar thing to implement on our [national indicators](https://sustainabledevelopment-deutschland.github.io/en/) platform. I would like to create a button that allows the user to download a pdf with all the indicator information, the Chart and the text passages from the metadata tabs. 
I have used html2pdf() for this, but am having some problems getting a decent layout. Anyway, to get the chart into the PDF, I used `document.getElementById('chart-canvas')` instead of all the content as you did above with `main-content`.

**Comment by WohnungNDS** [comment]
@MoBosse sounds great.... some kind of fact sheet for on indicator?

But the first question is where do I have to change my code that the button appears next to the other buttons into my indicator site?
To my mind it has to be possible to fill 

`var divToPrint=document.getElementById('**main-content**');`

with the current div that is shown on the indicator page...

for the table It might be this: <div id="selectionsTable">
for the chart It might be this: <div id="selectionsChart">
for the map It might be this: <div id="mapview">

But i am not familar with the html strucure of theindicator page.....

perhaps @LucyGwilliamAdmin or @brockfanning givew a hint ;-)
.

**Comment by MoBosse** [comment]
My first thought was that you would have to overwrite the [indicatorView ](https://github.com/open-sdg/open-sdg/blob/1.7.0-dev/_includes/assets/js/indicatorView.js) file for this because here is the `createDownloadButton` function that creates the green button underneath the chart aswell, but I am not sure about that.

**Comment by WohnungNDS** [comment]
@MoBosse may be..... but as I said before i am no familiar with js ...

perhaps we get a hint from the other users....
