### ISSUE TITLE
Embedded content gets blocked

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1586]
**Please complete the following information**
Data repository URL: [https://github.com/MoBosse/data-starter/blob/develop/indicator-config/1-1-1.yml](https://github.com/MoBosse/data-starter/blob/develop/indicator-config/1-1-1.yml)
Data or metadata issue: metadata

**Describe the bug**
Emedded content does not load on page. Console says "Loading of mixed active content [link] was blocked."
Tried with open-sdg 1.8.0, 1.7.0 and 1.6.0

See result [here](https://mobosse.github.io/site-starter/1-1-1/) (3rd data-tab)

**Comment by brockfanning** [comment]
@MoBosse Can you try with using "https" instead of "http" for the iframe URL? Because the Github.io URLs are https by default, any iframes are going to need to be https as well.

**Comment by brockfanning** [comment]
@MoBosse I haven't ever tried embedding a PDF file as an iframe source. From some quick searches, it does sound like that is possible, or at least has been possible in the past. I'm wondering if some browsers may have stopped supporting that. I saw this somewhat-recent blog post that recommends using an "embed" tag: https://www.codexworld.com/embed-pdf-document-file-in-html-web-page/. I wonder if you could use that embed tag approach in the "embedded_feature_html" instead of using "embedded_feature_url".
