### ISSUE TITLE
Low values in selection legend overlap poorly with text names

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1677]
When on a map, if you click on the regions the value is displayed in the top RHS next to the key for the upper and lower limits of the chart. However the text and values do not overlap cleanly leading to the region, value and the 'x' mark often looking messy. To reproduce load this map: https://sdgdata.gov.uk/3-3-3/ and click on some of the regions on the map. 

![image](https://user-images.githubusercontent.com/90769108/173811010-c1e72d2d-4eff-44b8-a7d5-de8778b6643c.png)

**Comment by brockfanning** [comment]
@otis-bath Hope you don't mind I'll rename the issue to clarify the root problem.

That "selection legend" (as we call it in the code) is certainly problematic as you point out. The problem is that we treat each item sort of like a horizontal bar chart, in that:
1. Each has a white bar which has a width according to the numeric value as a percentage. For example if the numeric value is 50 and that maximum is 100, then the white bar will be 50% width.
2. Each has a grey square which has the numeric value itself, positioned to the right of the white bar.
3. Each has its text name displayed on top of the white bar.

The above looks fine when the width of the white bar is longer than the width of the text name. But as shown in Otis' screenshot, this looks very bad when the width of the white bar is shorter than the width of the text name. Or put another way, it looks very bad when the numeric value of the item is low enough that the white bar is not longer than the text name.

I don't have any ideas for solutions. In the past I've floated the idea of removing that whole "selection legend", but I believe some users may like it. I'll try to find any relevant conversations.

Tagging @phillipgardiner for awareness.

**Comment by christoph-LSN** [comment]
@brockfanning may be it's possible to use the region names as a legend of the bar like in ecxel....
the legend entry has to be left from the bar an not within the bar

![image](https://user-images.githubusercontent.com/94443931/173849576-728d04f5-4536-4e7d-9259-2036e0a9aee3.png)

**Comment by brockfanning** [comment]
@christoph-LSN That seems like a good solution to me.

**Comment by brockfanning** [comment]
@otis-bath @christoph-LSN #1680 is an attempt to implement that idea of moving the names to the left. Feedback welcome.
