### ISSUE TITLE
How to set site.goal_image_base to site.baseurl

### ISSUE THREAD

**Issue by adborden** [open-sdg/open-sdg#172]
The image URLs for the goal tiles on the frontpage are built from `site.goal_image_base`, which based on the starter-site, points to open-sdg.github.io. However, I want the images to be hosted locally in the repo, so all assets on on our own domain. There is no way to set `site.goal_image_base` to `site.baseurl` without overriding several includes.

**Comment by adborden** [comment]
Setting `goal_image_base: .` might work for top-level pages, but not pages deeper than that. I think we can default to baseurl if goal_image_base is not set e.g. in the templates: `{{ site.goal_image_base | default: site.baseurl }}/assets/img/goals/...`

**Comment by brockfanning** [comment]
Hi @adborden, your idea of defaulting to site.baseurl sounds like a great improvement to me.

**Comment by brockfanning** [comment]
@adborden I did a quick PR but realized it was not sufficient, because site.goal_image_base right now is expected to include the /assets/img/goals path.

A workaround occurred to me that I'd like to run past you: duplicating the baseurl in the goal_image_base. For example, having this in the _config.yml:

```
baseurl: /my-base-url
goal_image_base: /my-base-url/assets/img/goals
```

One gotcha with that approach is that if the baseurl ever changed, the goal_image_base would need to change also. Do any other issues jump out at you?

**Comment by brockfanning** [comment]
Hopefully this workaround is working OK. I'll go ahead and close this, but feel free to re-open if needed.
