### ISSUE TITLE
Blank metadata fields 

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1726]
During previous usability testing it was found that blank rows in metadata effected participants trust and confidence in the site. We therefore need to ensure all rows within metadata have something written within them. Blanks rows make users question if something is missing that should be there. The following implementation has be evaluated with end users. 

**To do:** Implement ‘_Not available for this indicator_’ in all blank metadata fields. This text should be color: #505A5F;
    font-style: italic;. See example below.  

![image](https://user-images.githubusercontent.com/60919820/177302175-221712dd-53f8-4712-9d31-fc95954a5575.png)

**Comment by LucyGwilliamAdmin** [comment]
This needs to be considered alongside the existing option for blank metadata fields - completely hiding them.

Suggestion: implement config option e.g. `blank_metadata_fields`, which can be set to either some text (as above) which would be the default or hidden.

We could then see who's left hiding them and try to understand this from a user need perspective.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Can you help me understand the suggestion? Our existing config is called `hide_empty_metadata`. My first thought is that this new config could be called `empty_metadata_placeholder`. Note that if a country wanted to use this new `empty_metadata_placeholder` config, they would need to make sure that `hide_empty_metadata` was `false` (which is the default, although it is `true` in the site starter).

So the config to achieve this would be something like:

```
hide_empty_metadata: false
empty_metadata_placeholder: Not available for this indicator
```

Since `hide_empty_metadata` already defaults to false, then we could make `empty_metadata_placeholder` default to "Not available for this indicator". In other words Open SDG will automatically use "Not available for this indicator" if the `empty_metadata_placeholder` site config is either missing or `''`. So the above configuration would be used even if both config options were completely omitted.

This also means that it will be impossible for a country to continue displaying blank empty metadata fields. For example if a country currently has...

```
hide_empty_metadata: false
```

...and they have a metadata field "Foo" which is empty for an indicator, then their metadata is currently rendered something like this:

Label|Content
---|---
Some field|Some content for this field
Foo|
Some other field|Some other content for this other field

But then after this feature was implemented, their empty metadata would get that placeholder text. So it would then be rendered like this:

Label|Content
---|---
Some field|Some content for this field
Foo|Not available for this indicator
Some other field|Some other content for this other field

The country would not be able to go back to having blank empty metadata. If they were unhappy with having placeholder content, they would have to set `hide_empty_metadata` to remove the empty fields completely, after which their metadata would be rendered something like:

Label|Content
---|---
Some field|Some content for this field
Some other field|Some other content for this other field

Any concerns with this? Or did I misinterpret your suggestion?

If there is a concern with removing this "legacy" ability to have blank empty metadata, I guess we would need a third config option like `hide_empty_metadata_placeholder` which they could set to `true` (though it would default to `false`.) Using this they could achieve the current behavior (showing blank empty metadata) with this config:

```
hide_empty_metadata: false
hide_empty_metadata_placeholder: true
```

Hope that all makes sense, let me know what you think.
