### ISSUE TITLE
Possible problem with understanding the maps

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1792]
**Please complete the following information** 
Site repository URL: [https://github.com/DnsUpgradeEnvironment/dns-indicators](https://github.com/DnsUpgradeEnvironment/dns-indicators)
Open SDG version: 2.1.0-dev

**Describe the bug**
[Here](https://dnsupgradeenvironment.github.io/dns-indicators/en/3-1-cd/) we have an two time series ("adolescent smokers" and "adult smokers") we have two time series ("adolescent smokers" and "adult smokers") to be displayed on the same indicator page. To make them easier to compare, the two series are not named as "series" so that they can both be selected at the same time. Therefore, the chart/map title is not dynamic and applies to both series.
The problem is that only one of the series has geodata and is displayed in the map. The title is still "Proportion of adolescent and adult smokers", and since there is no other data to select in the map, only the unit is shown in the legend. The result is that the user has no way of telling whether the data shown in the map is for adolescents or adults.
![grafik](https://user-images.githubusercontent.com/50657629/186851547-5ae441fd-11ea-46a8-be86-002a61fc1fe0.png)

**To Reproduce**
1. Go to [https://dnsupgradeenvironment.github.io/dns-indicators/en/3-1-cd/](https://dnsupgradeenvironment.github.io/dns-indicators/en/3-1-cd/)
2. Click on map
3. See error

**Expected behavior**
I could think of two possible solutions:

1. There could be a separate title for maps that (if defined) overrides the chart title.
2. All disaggregation columns that are filled for the map datasets must be displayed in the map legend (even if the disaggregation cannot be changed)

**Comment by brockfanning** [comment]
@MoBosse Both of those solutions seem reasonable - and in particular I think there is a clear need for the second one - displaying disaggregation columns even if they can't be changed. That's important information that should be displayed.

I believe the problem is here: https://github.com/open-sdg/open-sdg/blob/2.1.0-dev/_includes/assets/js/plugins/leaflet.disaggregationControls.js#L49-L79

If you replace all that code with `return disaggregations;` I think you'll see your "time series" column. But the problem is that you'll also see your "federal state" column. So the challenge, I think, is to figure out how we can hide the "federal state" column but still show the "time series" column.

I wonder if there is an efficient way for Open SDG to identify that a column corresponds to regions on the map. If so, we could just hide that column ("federal state" in this case) and display all the others.

**Comment by brockfanning** [comment]
@MoBosse Here is an experimental try at this - maybe you could work this code change into your override: https://github.com/open-sdg/open-sdg/pull/1795

**Comment by MoBosse** [comment]
It may be a bit clumsy but [this aproach](https://github.com/DnsUpgradeEnvironment/dns-indicators/commit/fc02f37322153b22412cc83c47d1b4bed929e136) seems to avoid showing the button when there is nothing to change.

**Comment by brockfanning** [comment]
@MoBosse I think we are thinking the same thing - I just pushed a similar change to the PR.

**Comment by MoBosse** [comment]
Fixed by #1795
