### ISSUE TITLE
DAC_Headings_and_Labels_01 Issue

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#1840]
URL:http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-2.1.0-beta2/

Issue raised in DAC report - screen reader users did not find the label ‘toggle navigation’ to sufficiently describe the purpose of the menu button.

When you land on the page, the aria-label is ‘Toggle navigation’ but once you’ve opened it once, the aria-label is ‘Show navigation menu’ when it’s not expanded and ‘Hide navigation menu’ when it is expanded.

**Comment by brockfanning** [comment]
@sarah-beasley I believe this is a UK-specific issue because of an override - see this line: https://github.com/ONSdigital/sdg-indicators/blob/develop/_includes/header.html#L22

**Comment by sarah-beasley** [comment]
Thanks @brockfanning , does this mean I need to make a change on sdg indicators now?

**Comment by brockfanning** [comment]
@sarah-beasley Yes - in that line you could change "Toggle navigation" to "Show navigation menu".

**Comment by sarah-beasley** [comment]
Sorry @brockfanning i'm getting a bit confused as the wording needs to change from 'hide' to 'show' depending on whether the areas-expanded=true or false. i've tried adding just that bit to the code but it hasn't worked. do i need to add a whole new line like this underneath, inline with what the inspect code says? 
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Hide navigation menu">

**Comment by brockfanning** [comment]
@sarah-beasley No problem, it's confusing because some parts of this fix are in 2.1.0. I would recommend making this fix in the 2.1.0-beta2 feature branch (or 2.1.0-beta3 when it is created) so that you can benefit from the latest code. The only change you need to make is [the first commit that you made](https://github.com/ONSdigital/sdg-indicators/commit/333ef00d2e28f588a9bfcd49ac6b522ca7b35bc7) (changing "Toggle navigation" to "Show navigation menu". You don't need to worry about the dynamic part of this, as that has been fixed already in the latest code.
