### ISSUE TITLE
I am trying to add new page in a new branch. Initially there was issue with ruby version. I solved it but now it is showing issue with testing the HTML while creating pull request

### ISSUE THREAD

**Issue by MeghaStha** [open-sdg/open-sdg#1899]
**Please complete the following information** 
Site repository URL: https://github.com/MeghaStha/AuburnSite
Open SDG version: 1.0.0

**Describe the bug**

**To Reproduce**
1. After adding the example.md file
2. Commit changes
3. Create pull request
4. Ruby version issue
5. Changed the workflow folder to ruby/ruby@v1
6. Tried to commit again
7. Testing fails at the stage of test the HTML

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

![image](https://user-images.githubusercontent.com/9130639/207979239-047f0a41-16d6-4059-abc6-8fb8c3e548dd.png)

**Comment by christoph-LSN** [comment]
Hello @MeghaStha, 

I have the same problems. If I merge changes into my master branche I get a lot of html checker errors as you can see here: https://github.com/christoph-LSN/MT_Site/actions/runs/3683637214/jobs/6232439820

But even I get this errors my production site starts doing updates and everything works fine. 

Perhaps @MoBosse has an idea....

**Comment by MoBosse** [comment]
Hi @MeghaStha,
I recently had some [trouble ](https://github.com/open-sdg/open-sdg/discussions/1885) that seem familiar at first glance. Thing is, I am not entirely sure how I solved it.
There is one thing that comes to my mind you could try: You may need to add the `example.md` to the [es](https://github.com/MeghaStha/AuburnSite/tree/develop/_pages/es) folder aswell (with adjustments to "language" and "permalink" of course).

**Comment by MeghaStha** [comment]
@christoph-LSN I tried reloading the page. I don’t see any changes.

**Comment by MeghaStha** [comment]
@MoBosse I have added the example.md file to es folder but it didn’t work. Do you have any other suggestion?

**Comment by brockfanning** [comment]
@MeghaStha @christoph-LSN @MoBosse If you are not already, I would recommend "pinning" htmlproofer to an older version. The htmlproofer project has lately been making a lot of very opinionated changes that cause tests to fail in new and unexpected ways. We have updated the site starter repository so that htmlproofer is pinned to an older version. You can see that in the [Gemfile here](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/Gemfile#L4). The relevant line is:

```
gem "html-proofer", "3.19.4"
```

I believe that doing this -- and also adding the Spanish version of example.md as @MoBosse pointed out -- should help get the tests to pass again. If you are comfortable with doing this, I would recommend making both of these changes _in the same branch_. However you could instead temporarily turn off the automated tests, which would allow you to merge pull-requests even if tests fail.

**Comment by MeghaStha** [comment]
Thank you so much. It finally worked. Pinning the htmlproofer to an older version did the trick.
