### ISSUE TITLE
I am trying to add information of indicator 1.1.1 as csv file directly into the data folder of my data repo. After I commit and merge the change I get a notification that the deploy to staging has failed. I relatively new to this. I read the documentation as well but I am confused about what I am doing wrong.

### ISSUE THREAD

**Issue by MeghaStha** [open-sdg/open-sdg#1904]
**Please complete the following information**
Data repository URL: https://github.com/MeghaStha/AuburnAldataRepo/tree/develop/data
Data or metadata issue:
Input format:CSV

**Describe the bug**
I can add the information as csv. It is formatted based on the suggestions in the documentation. After I commit changes the deploy to staging fails and I cannot see any changes. 

![image](https://user-images.githubusercontent.com/9130639/208812634-4411ae2a-2a5c-4450-8f6f-2fad135dbbb2.png)

**Comment by christoph-LSN** [comment]
@MeghaStha 

Perhaps you can try to  add a _blank_ between > and 1.1.1

https://github.com/MeghaStha/AuburnAldataRepo/blob/3a46ccb08f763cb7fd4e8b52a6187dc3dd6ed82d/meta/1-1-1.yml#L10

**Comment by brockfanning** [comment]
Adding the blank space there could work yes, or maybe a line break, eg:

```
SDG_SERIES_DESCR: >-
  1.1.1
```

However FYI I believe the `>-` is usually for multiline values. If it is a short value like `1.1.1` then you could also use this simpler syntax:

```
SDG_SERIES_DESCR: 1.1.1
```

Also a helpful tip - in general it is best to create pull-requests rather than committing directly to the develop branch, because then any problems will be caught by the automated tests. This issue highlights that, because it appeared to you that the problem was in the CSV file, but in actuality it was in the YAML file. The only way to track down the actual culprit is to go into the [Actions](https://github.com/MeghaStha/AuburnAldataRepo/actions) section and look for the oldest commit that caused a failure -- which at the moment is "Update 1-1-1.yml".

**Comment by MeghaStha** [comment]
Thank you. It worked.
