### ISSUE TITLE
graph_title not showing on feature branch

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#1969]
**Please complete the following information**
Data repository URL: [[e.g. github.com/ONSdigital/sdg-data](https://github.com/ONSdigital/sdg-data/tree/feature-17-4-1)]
Data or metadata issue: Data - graph_title being changed in the .md file but not showing up on the feature branch.
Input format: [Markdown]

**Describe the bug**
Trying to change the graph title of 17-4-1 from “Debt service as a proportion of exports of goods and services”, to “Gross debt as a proportion of total trade worldwide exports”, however the change is not appearing on the feature branch as usual when changing the graph_title field in the .md file for the indicator.

**Additional context**
[Feature branch ](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-17-4-1)not showing graph title change.

**Comment by sarah-beasley** [comment]
@christoph-LSN yes i did do that to check too, but nothing changed!

**Comment by brockfanning** [comment]
@sarah-beasley There is a site configuration `graph_title_from_series` that is set to `true`. In this case this actually overrides the `graph_title` when an indicator's data include a `Series` column. All of the rows in 17.4.1's data have a Series of `Debt service as a...`: https://github.com/ONSdigital/sdg-data/blob/feature-17-4-1/data/indicator_17-4-1.csv

So I think, rather than setting the graph_title indicator configuration, the best way to control the graph title is to change the values in the Series column of the CSV file.

**Comment by sarah-beasley** [comment]
Thanks @brockfanning , we have decided to use graph_titles instead of graph_title to overcome this which means we can keep the graph_title_from_series in the site_config.yml to stay as true. We have considered changing this to false, but are not sure which indicators rely on this feature at the moment so makes sense to keep it for now.
