### ISSUE TITLE
Reporting Status Page - Disaggregation (option to remove out of scope)

### ISSUE THREAD

**Issue by Govej** [open-sdg/open-sdg#2009]
(To be discussed with the UK data team to identify their exact needs)

**Comment by AaronONS** [comment]
Design changes made to disaggregation status, so that 'out of scope' are not included on the visualization. Effectively we now only show indicators where a disaggregation is explicitly mentioned in the indicator title. 

![Image](https://github.com/open-sdg/open-sdg/assets/115177251/06a2bb82-39fe-4ebb-b02e-2a36ef541f57)

When we have a feature branch the data team will make changes to the text at top of reporting status page to reflect this. 

This should be included in Open SDG - an option to display disaggregation in 'classic' format or in this way. 

When have FB will try and slot into some other user testing going on.

**Comment by sarah-beasley** [comment]
Make as an option so users can choose whether they want to implement
