### ISSUE TITLE
Checkboxes get selected when changing unit

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#2012]
**Please complete the following information** 
Site repository URL: [https://github.com/MoBosse/site-starter](https://github.com/MoBosse/site-starter)
Open SDG version: [e.g. 2.2.0]

**Describe the bug**
I have a case where I have 3 time series with 2 different units (A and B are of unit % and C is of unit number).
When I select all three series, change the unit from % to number, deselect series B and then change back to %, the behavior of the chart is as expected (showing only A), however the checkbox of B is selected again.

**To Reproduce**
1. Go to [https://mobosse.github.io/site-starter/1-1-1/](https://mobosse.github.io/site-starter/1-1-1/)
2. Select all series (A, B & C)
3. Switch to number
4. Deselect B
5. Switch back to percentage
6. See how B is not shown (as is correct) but check box is selected again

**Expected behavior**
The check boxes should remain in the state in which they were selected by the user.

**Screenshots**

All series are selected (everything correct)
![grafik](https://github.com/open-sdg/open-sdg/assets/50657629/27f82022-3eb9-42c2-93b0-3dc5074b6b8d)

After having changed to "number", deselecting B, and switching back to "%" (see how B is selected again but not shown):
![grafik](https://github.com/open-sdg/open-sdg/assets/50657629/44a08915-1b1a-4ccb-b7d9-aa9b90874975)

**Additional context**
The behaviour described does not seem to apply to the lower level disaggregations.

**Comment by christoph-LSN** [comment]
perhaps you can try to set data_start_values for each unit?

**Comment by MoBosse** [comment]
@christoph-LSN I did. Start_values have no effect on the issue.

**Comment by brockfanning** [comment]
@MoBosse I'm trying to wrap my brain around this issue to decide where the bug starts. Can I ask your opinion on something?

If I go to https://mobosse.github.io/site-starter/1-1-1/ and open the "timeseries" dropdown, there are checkboxes for "A", "B", and "C". However there is no data in the CSV for "C" in that unit. So, I can check the box for "C" but it doesn't affect the chart at all.

Do you consider this a bug (the fact that the "C" box appears even though there is no data for it in the current unit)? In other words, should the dropdown only have checkboxes for "A" and "B" when "percentage" is the current unit?

Or instead are you happy with that aspect of the current behavior, with checkboxes appearing even if there are no data for them in the current unit?

**Comment by MoBosse** [comment]
@brockfanning  Come to think of it, yes, I guess I would expect only checkboxes A and B to be displayed when "percentage" is the current unit, and then a selected checkbox C to be displayed when the unit is set to "number".

**Comment by brockfanning** [comment]
@MoBosse At first I thought we could address that larger issue, but I ran into some questions that I'm not sure about. For example, in the above scenario, is it going to be confusing to the user that they had "A" and "B" selected, and then suddenly "C" is selected because they changed units?

This seems like a potentially thorny problem that could use more careful consideration. My memory is that our general philosophy with Open SDG has been to give the user full control, and try not to change selections without the user intentionally doing something. This does mean they might end up with no data on the chart, but we try to make that clear with the "no data" message.

This has alerted me to a specific problem that could maybe be addressed in a separate issue: It is possible for a user to select a checkbox that does not change the displayed data at all. For example in the scenarios above, the user can switch to "percentage" and then select "C". This appears to refresh the chart, but does not actually add anything to it. It's not a major problem but I think I little confusing.

Meanwhile I think I've got a simpler fix for the original problem you described, where the checkbox is becoming selected. Can you try out #2068? It seems to work for me, but I think it needs testing, especially to make sure it doesn't cause any problems elsewhere.

**Comment by MoBosse** [comment]
@brockfanning Thanks for the PR. On the page I created to explain the issue it works great. I now implemented it on a copy of our actual site to see if it causes any other unexpected issues but couldn`t find any so far.

**Comment by brockfanning** [comment]
@MoBosse I made a quick change to the PR in the hopes that it would fix it. As before, I'm always interested in confirming that it has no unintended consequences on normal indicators.

**Comment by MoBosse** [comment]
@brockfanning Looks good. I'm now testing in our actual environment. If I come across any unexpected behaviours, I'll let you know. Thanks!
