### ISSUE TITLE
Update to 2.2.0  /  2.3.0-dev is failing

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#2027]
**Please complete the following information**
[Data](https://github.com/christoph-LSN/IM_Data/)
[Site](https://github.com/christoph-LSN/MT_Site/)
[staging site[(https://christoph-lsn.github.io/MT_Site/)

**Describe the bug**
I tried to update my repos to version 2.3.0-dev.  in the site repo it works for the _config. yml without errors.
Change the Gemfile to 2.3.0-dev the following error is shown:

```
  * jekyll-open-sdg-plugins-2.1.0
  * jekyll-open-sdg-plugins-2.2.0.pre.beta1
  * jekyll-open-sdg-plugins-2.2.0
Error: Process completed with exit code 7.
```
https://github.com/christoph-LSN/MT_Site/actions/runs/5576431225/jobs/10187694327

If I try to update my reqirements.txt to 2.2.0 or 2.3.0-dev the following error is shown:

```
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/sdg/translations/TranslationInputYaml.py", line 64, in parse_yaml
    value = yamldata[key]
TypeError: list indices must be integers or slices, not dict
Error: Process completed with exit code 1.
```
https://github.com/christoph-LSN/IM_Data/actions/runs/5576615066/jobs/10188173759?pr=28

**Additional context**

At the first glance everything is working well with

[_config.yml](https://github.com/christoph-LSN/MT_Site/blob/develop/_config.yml) pointing to 2.3.0-dev
[gemfile ](https://github.com/christoph-LSN/MT_Site/blob/develop/Gemfile)gem "jekyll-open-sdg-plugins", "2.2.0"
and [requrements.txt](https://github.com/christoph-LSN/IM_Data/blob/develop/scripts/requirements.txt) git+https://github.com/open-sdg/sdg-build@2.1.0

Any ideas @MoBosse @brockfanning @sarah-beasley

**Comment by brockfanning** [comment]
@christoph-LSN 

Regarding the Gemfile, it is a little bit weird. You can't refer to a branch of open-sdg using this syntax (the following will not work):

```
gem "jekyll-open-sdg-plugins", "2.3.0-dev"
```

The reason is that when you use that syntax, you are "looking" for jekyll-open-sdg-plugins in the rubygems.org catalog of plugins. Here you can see the versions that are available there: https://rubygems.org/gems/jekyll-open-sdg-plugins. As you can see there are no versions called "2.3.0-dev", which is because 2.3.0-dev is only a branch in Github, but has not been turned into a "release" on rubygems.org.

However it IS possible to point to a branch on Github instead of rubygems.org, by using a different syntax. To do that, you would use this (the following will work):

```
gem 'jekyll-open-sdg-plugins', git: 'https://github.com/open-sdg/jekyll-open-sdg-plugins.git', branch: '2.3.0-dev'
```

Regarding the error you're getting in the data build:

```
 File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/sdg/translations/TranslationInputYaml.py", line 64, in parse_yaml
    value = yamldata[key]
TypeError: list indices must be integers or slices, not dict
Error: Process completed with exit code 1.
```

In version 2.2.0 we updated the code a bit so that the build will actually fail when there are YAML syntax problems, rather than silently skipping things. In other words, prior to 2.2.0, when there are YAML syntax problems, the whole YAML file is silently skipped. But with 2.2.0 it should actually give an error and halt the build. That was done in this PR: https://github.com/open-sdg/sdg-build/pull/336

So my first thought would be to take a look at your translation YAML files. I'm wondering if there is a problem in one of them, like maybe one of the following:
* Usage of `:` in a value without wrapping the value in `""`
* Usage of a `"` in a value without wrapping the value in `''`
* Usage of a `'` in a value without wrapping the value in `""`

(I think it is usually the `'`, `"`, and `:` characters that cause the most YAML syntax issues.)

**Comment by christoph-LSN** [comment]
@brockfanning Thank you fot the advice for the gem file. 

I have checked my yml files with this code:

```
<!DOCTYPE html>
<html>
<head>
    <title>YAML Validation</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js"></script>
</head>
<body>
    <input type="file" id="yamlFileInput" multiple>
    <button onclick="validateYaml()">Validate YAML</button>
    <div id="validationResult"></div>

    <script>
        function validateYaml() {
            const fileInput = document.getElementById('yamlFileInput');
            const validationResult = document.getElementById('validationResult');
            const files = fileInput.files;

            if (files.length === 0) {
                validationResult.innerText = 'Please select at least one YAML file.';
                return;
            }

            for (let i = 0; i < files.length; i++) {
                const file = files[i];
                const reader = new FileReader();

                reader.onload = function(event) {
                    try {
                        const yamlContent = event.target.result;
                        jsyaml.load(yamlContent);
                        validationResult.innerText = 'Valid YAML: ' + file.name;
                    } catch (error) {
                        validationResult.innerText = 'Invalid YAML - ' + file.name + ': ' + error.message;
                    }
                };

                reader.readAsText(file);
            }
        }
    </script>
</body>
</html>
```
They are all valid. Can I get a hint from the logfile which yml file causes the mentioned error?

**Comment by brockfanning** [comment]
@christoph-LSN I'm wondering if it's caused by this "www" folder being there: https://github.com/christoph-LSN/IM_Data/tree/develop/translations/www. That seems like it would cause a problem, and I'd bet that folder isn't supposed to be there.

**Comment by christoph-LSN** [comment]
@brockfanning may be...
I will try later today do add a new folder with the following structure:

```
-IM_translastions
     -translations
         -de (containing my yml files)
     -www
         -_data
         - assets
         - ...

```

**Comment by christoph-LSN** [comment]
@brockfanning I tried to fork the sdg-traslations repo. unfortunatly ia pushed a pull request.... sorry for that.

**Comment by christoph-LSN** [comment]
@brockfanning finally it works with sdg-build@2.2.0 ! Thank you!

I forked the sdg-translations repo and filled in my yml files from my local translation folder.
And I also get rid of the problem wit my goal image base, which points to my old WohnungNDS/IM_Data repo and won't work with my local translations folder.

So thank you @brockfanning 

may be this aproach is interesting for you too @SandraEliz
