### ISSUE TITLE
Indicator code seems to appearing twice in indicator title

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#203]
Since upgrading to open-sdg, the indicator code is appearing twice in indicator title i.e. in coloured bar:
![image](https://user-images.githubusercontent.com/43404358/59445178-1200ed80-8df7-11e9-878d-50be0d9879e9.png)

I have tested this on this [feature branch](https://sdg.mango-solutions.com/remove-unneeded-overwritten-files/) where I have deleted the files indicator.html and indicatorView, which were overwriting open-sdg but still have problem

**Comment by LucyGwilliamAdmin** [comment]
Ok, not an issue as such as I can see that this has come from [this commit](https://github.com/open-sdg/open-sdg/commit/c9f00a7e652c3f454bb05bbf1582c492f7028c44#diff-1f91213e222687fd55c5b47cc1e8c48d). So does this mean, that the indicator title comes from our metadata files rather than from the translations repo?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Ah I see. Yes it looks like this is causing some undesired behavior. [This line](https://github.com/open-sdg/jekyll-open-sdg-plugins/blob/master/lib/jekyll-open-sdg-plugins/get_indicator_name.rb#L74) is getting the 'indicator_name' from the metadata, instead of going on to the next section, which gets the global translation.

So it sounds like you would prefer that the global translation be given a higher priority than the metadata's 'indicator_name'. I'll need to think on it a bit and see what we can do.

**Comment by brockfanning** [comment]
I'm going to do an audit of all the places on the platform that the indicator names are displayed, and where they're getting the data from. I'll report back soon.

**Comment by brockfanning** [comment]
@Norric1Admin @LucyGwilliamAdmin I've got a PR up [here](https://github.com/ONSdigital/sdg-indicators/pull/3177) that should fix this. In a nutshell, I've made a tweak that changes the "get_indicator_name" filter to prefer the global name above the 'indicator_name' field.

**Comment by LucyGwilliamAdmin** [comment]
This worked great, thanks!
