### ISSUE TITLE
download button type consistency

### ISSUE THREAD

**Issue by AaronONS** [open-sdg/open-sdg#2031]
brock to estimate.

DAC Usability issue
User interface components were styled to look like different component types.

There are links are styled as buttons. This means that the visual styling did not correspond with the role of the component. Voice activation users will not be able to access the components as expected using the command ‘click button’.

Voice activation user comments: “The ‘download chart’ button is picked up as a button by Dragon but the others are picked up as a link. I found this confusing as they have a similar appearance so I expected them to be picked up as the same element type.”

URL
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/datapreview_15-2-1/15-2-1/

Solution:
It is advised to style elements corresponding with their semantic role. This will also ensure that Keyboard Only users can interact with controls in the expected way, and that Voice activation users are able to reference the control by role, for example, by using the corresponding command ‘click button’ or ‘click link’.

e.g. make them buttons

Note: Additional information can be found in: Accessibility Audit Report for ONS SDG, 21/04/2021, ref-000699 p.45

**Comment by sarah-beasley** [comment]
Ask question to DAC - is it ok to use links with the button role, or do they need to be buttons?

**Comment by sarah-beasley** [comment]
From DAC: implementing the ‘role=”button”’ attribute on a native link is sufficient as this attribute will override the semantics implied by the <a> tag. This will ensure that when the component is encountered by screen reader users it will be detected as a button and not a link. 

Please note: Using the correct HTML tags for buttons and links is important because it can disorient users if they hear the wrong tag read out to them by the screen reader. As links are used for navigation and buttons are used for actions, when screen reader users hear “link” or “button,” they have a specific expectation for what that element will do if triggered. For example, if a link has a role=”button” on it and is read out to users as a button, they might click it expecting an action to be performed on the current page; when a new page opens instead, this can lead to confusion and frustration.
