### ISSUE TITLE
Sources 7 and up not showing in Sources tab

### ISSUE THREAD

**Issue by Zelheim** [open-sdg/open-sdg#2073]
**Please complete the following information** 
Site repository URL: https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd and https://github.com/sdg-data-canada-odd-donnees/sdg-odd-dev
Open SDG version: 2.2.0

**Describe the bug**
When there are more than 6 sources for any given indicator, Source 7 and up do not show up in the Sources tab.

**To Reproduce**
1. Go to https://sdg-data-canada-odd-donnees.github.io/sdg-odd-dev/1-4-1/
2. Click on Sources
3. Scroll down to the bottom of the tab

**Expected behavior**
Source 7 and up should be showing up in the Sources tab

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser: Edge
 - Version: 110.0.1587.46 (Official build) (64-bit)

**Comment by brockfanning** [comment]
@Zelheim If you check out your metadata_schema.yml file, you'll see that there are only entries for the source_* fields going up to 6: https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/blob/develop/metadata_schema.yml

In order to display up to 8, you'll need to add entries in this file for 7 and 8. I think you can just duplicate the entries for 6 and then change "_6" to "_7" (and again for _8).

By the way, on the subject of sources, we have an alternative way to keep track of your sources that you might consider, if you're interested. One benefit of the alternative way is that there is no limit on the number of sources. There's more information on this here: https://open-sdg.readthedocs.io/en/latest/indicator-configuration/#sources. Let me know if you would like any help with implementing that, or if it doesn't meet your needs.

**Comment by Zelheim** [comment]
@brockfanning Perfect! Thank you for helping with this issue! For now, I will implement a quick fix by adding extra sources within the metadata_schema.yml file, but I will see to implement what you have linked within the Open SDG documentation in the future!!

Thank you again for your help!!
