### ISSUE TITLE
Another tab for News/Updates

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#218]
Request from Kyrgyzstan: "We would like to have News page or «SDG in action» and publish all news, activities, useful materials related to SDG"

Also I think Abdulla brought something similar up in the Cambodia call - he says it's very important for countries to have this page (especially for VNR as VNR is not just about data)

UK are also interested in having this sort of page.

**Comment by brockfanning** [comment]
There is some undocumented functionality already in place that approaches this. Jekyll, out of the box, comes with a ["_posts" folder](https://github.com/open-sdg/open-sdg-site-starter/tree/develop/_posts). You can add files inside that folder named according to this convention: `YEAR-MONTH-DAY-TITLE.md` (eg, `2019-07-03-my-title.md`). The contents of the files should be something like:
```
---
layout: post
title: My title
---
This is my post's content.
```

There is also already a [listing page for these posts](https://github.com/open-sdg/open-sdg/blob/master/_layouts/news.html), at the path: `/news/`.

This is a little-used part of the platform, but I believe it's still functional. Maybe we should start by exploring this functionality and then seeing if it lacks anything or needs any polishing.

Since this is generally out-of-the-box Jekyll, there is also some [Jekyll documentation](https://jekyllrb.com/docs/posts/) about it.

**Comment by LucyGwilliamAdmin** [comment]
I have created this [feature branch](https://sdg.mango-solutions.com/news-tab/news/) which has a news tab.

One thing I have noticed is that even though the image shows in the markdown file, it's not actually showing properly on the blog post. I have tried adding the image with md and html and get the same result for both - can be seen [here](https://sdg.mango-solutions.com/news-tab/news/2005/07/19/what-we-do.html)

**Comment by LucyGwilliamAdmin** [comment]
We in the UK would also like the functionality for comments to be added to a blog post. Looking into this now [here](https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe the image issue is related to the src URL being used. Does it work with this one? https://onsdigital.github.io/sdg-indicators/public/sdgs.png

Comments is always a tough feature for static sites. Disqus is definitely the easiest, but I agree with that post about the ads being problematic. That post seems like an interesting approach, and seems similar to what [Staticman](https://staticman.net/) does. [This approach](https://danyow.net/using-github-issues-for-blog-comments/) using Github issues also seems like a reasonable approach too, since Github is already an integral part of this platform. [Here](https://darekkay.com/blog/static-site-comments/) is a good overview of options, too.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning perfect - that fixed the image problem, thanks!

Ok great, will look into those too

**Comment by VincentTam** [comment]
> We in the UK would also like the functionality for comments to be added to a blog post. Looking into this now [here](https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/)

Here's some shortcomings of popular non-static commenting systems.

1. Gitment, Gitalk and Utterance support only GitHub, and they require user login before commenting. This can scare away many non programmers from leaving a comment to your posts. Besides, comments are part of the site's static content, not a software package problem. As a result, using GtiHub issues for comment storage is wrong in principle and bad in terms of SEO.
2. Commento is not free as in free beer.  For a personal blog with small traffic, you might find a monthly fee of $5 too expensive.
3. Disqus and Isso contain a 3rd-party script to be loaded during page rendering. The code block for loading each of them shows that the static comments are not rendered as static HTML code. This hinders search engines from grabbing the comments, which are part of the site's content.  As a result, that leads to suboptimal SEO.

One may avoid these problems by switching to Staticman, which makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

Since static comments are stored inside GitHub/GitLab repo as data files, one can do whatever one wants with them.  Here's an example with nested comments and math rendering support.

![math in comments](https://camo.githubusercontent.com/60e914a9c5de08ad7b547036f9336361c37acba8/687474703a2f2f696d6775722e636f6d2f4b5254744a4c586c2e706e67)

Concerning spam, despite Staticman's Akismet support, the relevant parameter is in the server-side API config.  A self-hosted instance allows customizing that parameter.

**Comment by brockfanning** [comment]
I think this is resolved. We can open a new issue to discuss commenting if that's a feature to pursue.
