### ISSUE TITLE
Divided source fields

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#276]
The Armenian version of SDG platform (https://armstat.github.io/sdg-site-armenia/ ) we would like it to be change :

a) The two source columns should become a 1 column.
b) all the fields should be removed and only some of them (Organisation, Data source, Link to data source, Contact details, Other information) must include there.
c) in the "ORGANISATION" field if there are more than 2 sources, it should be divided with comma 
(For example Armstat, Ministry of Economy of RA).

**Comment by brockfanning** [comment]
@SDGArmenia The short answer is:
1. Remove excess fields from the `_prose.yml` file (in your data repo)
2. Override the `_includes/components/sources.html` file (in your site repo) as needed

Here is the longer, more detailed answer...

1. **Remove excess fields from the `_prose.yml` file (in your data repo)**: This is the easier task: All you need to do is remove them from your [_prose.yml](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml) file. Note that there are six of each one. For example, to remove "Periodicity", you would want to remove it [here](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml#L209), [here](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml#L276), [here](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml#L343), [here](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml#L410), [here](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml#L477), and [here](https://github.com/armstat/sdg-data-armenia/blob/develop/_prose.yml#L544). This will have the effect of removing the field from your "schema", which will prevent Open SDG from displaying it.
2. **Override the `_includes/components/sources.html` file (in your site repo) as needed**: The next task is to make multiple Sources appear in one column. It sounds like you would prefer to only use data from Source 1, but gather the "Organisation" data from all Sources (Source 2, Source 3, etc.). To do this, override the markup by creating your own version of the `_includes/components/sources.html` file. Because you can control this version, you can tailor it to your own needs. Here is an example of what you might do:

```
<table class="table table-hover">

  <!-- The organisation field -->
  <tr>
    <th scope="row">{{ t.metadata_fields.source_organisation_1 }}</th>
    <td>
      {{ meta.source_organisation_1 | t }}
      {% if meta.source_active_2 %}
        , {{ meta.source_organisation_2 | t }}
      {% endif %}
      {% if meta.source_active_3 %}
        , {{ meta.source_organisation_3 | t }}
      {% endif %}
    </td>
  </tr>

  <!-- The link field -->
  <tr>
    <th scope="row">{{ t.metadata_fields.source_url_1 }}</th>
    <td>
      <a href="{{ meta.source_url_1 }}" target="_blank">
        {{ meta.source_url_text_1 | t }}
      </a>
    </td>
  </tr>

  <!-- The contact field -->
  <tr>
    <th scope="row">{{ t.metadata_fields.source_contact_1 }}</th>
    <td>{{ meta.source_contact_1 | t }}</td>
  </tr>

  <!-- The other information field -->
  <tr>
    <th scope="row">{{ t.metadata_fields.source_other_info_1 }}</th>
    <td>{{ meta.source_other_info_1 | t }}</td>
  </tr>

</table>
```
Note about the code above: You can see that it checks for an organisation in source 1, 2, and 3. If you think you might need 4 or more sources, you could add more `if` statements there.

If you are curious about the syntax of the `{% ... %}` stuff, see the [Liquid documentation](https://shopify.github.io/liquid/basics/introduction/).

**Comment by brockfanning** [comment]
@SDGArmenia It looks like you were able to get this working. Did you have any other questions about it?

**Comment by brockfanning** [comment]
I think this is resolved, so I'll close. But feel free to re-open with any questions or concerns.
