### ISSUE TITLE
Translation of 'names' from geojson files

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#298]
The names in the Geojson files are usually either in English or the national language. Is it possible to translate them into the chosen language (e.g. Bayern to Bavaria)?

**Comment by brockfanning** [comment]
Just like translations of other disaggregations, the translations of regional names can be controlled in the special `data` translation group. [Here](https://github.com/kazstat/sdg-site-kazstat/blob/develop/data/translations/en/data.yml#L12) is an example of a country doing this. The results can be seen [here](https://kazstat.github.io/sdg-site-kazstat/3-1-1/).

The reason I say that the "data" translation group is "special", is that Open SDG automatically looks for a translation inside this group, whenever it is rendering disaggregations. This convenience is to prevent data managers from having to add "data." to all the disaggregations. For example instead of needing to have:

Year | data.Region | Value
---- | ---- | ----
2019 | data.Northern Territory | 1
2019 | data.Southern Territory | 2

They can just use:

Year | Region | Value
---- | ---- | ----
2019 | Northern Territory | 1
2019 | Southern Territory | 2

This is briefly mentioned in the docs [here](https://open-sdg.readthedocs.io/en/latest/translation/#translating-data-disaggregations-and-columns).

**Comment by MoBosse** [comment]
All right. Thank you!
