### ISSUE TITLE
Merging error

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#301]
During the merging process of a new indicator, We get this error :

![error3](https://user-images.githubusercontent.com/46884106/63090236-bcb69900-bf6b-11e9-8492-ee4e816f9208.jpg)
.

**Comment by LucyGwilliamAdmin** [comment]
@SDGArmenia this error is being caused by the CSV file. If you look at the bottom there are some trailing white spaces in the Access to services column:
![image](https://user-images.githubusercontent.com/43404358/63092667-5ffeb280-bf5a-11e9-8e9f-0ae9329bcc90.png)
Once these are removed, this error should be resolved.

**Comment by brockfanning** [comment]
It looks like this resolved the problem. @SDGArmenia feel free to re-open if there are any more questions about this!
