### ISSUE TITLE
Disclaimer overhangs on mobile

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#305]
![image](https://user-images.githubusercontent.com/43404358/63190025-35495280-c05d-11e9-9894-5abd43cf5f66.png)

**Comment by brockfanning** [comment]
There's an inherent conflict here because the height could be variable, depending on how much text a country puts into the disclaimer. But because the disclaimer is currently "fixed" (always visible at the top of the page) we've got to hardcode the height.

Let me ask this - what about the possibility of the disclaimer _not_ being fixed? This would mean that when the user scrolled down the page, the disclaimer would not be visible. But it would also mean that we would not have to deal with this conflict about the height. Do you think this would be acceptable?

**Comment by brockfanning** [comment]
As a proof-of-concept for that I approach, I pushed up this branch: #309
