### ISSUE TITLE
Numeric disaggregation columns cause issues

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#327]
This is more of a hunch, and needs confirmation. It seems likely that numeric disaggregation columns may cause problems:
* Empty options in the disaggregation widget on the left
* Empty table and/or javascript errors

This is a follow up from #293

**Comment by christoph4711** [comment]
A further confirmation, numeric disaggregation columns causing errors;
I tried to use the map functionality and adding a column "Geocode" in my csv file.

Find my csv file [here ](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/data/indicator_1-5-1.csv)

No Map is shown an the dissaggregation widget [here](https://christoph4711.github.io/open-sdg-site-starter/1-5-1/) doesn't work correct....

**Comment by MoBosse** [comment]
@christoph4711: Try to write "GeoCode" (case sensitive) in the head of the csv column. Should actually fix this.

**Comment by christoph4711** [comment]
@MoBosse

Thank you so much! 
Now the dissaggregation widget, table and graph working fine. 

But the map doen't work completly.... 

![Map](https://user-images.githubusercontent.com/53389268/63747773-37ef4780-c8a8-11e9-8687-1fd169a2c87e.PNG)

maybe you can have a look at my answer/question [here](https://github.com/open-sdg/open-sdg/issues/293#issuecomment-524884141) concerning geojson etc.

If it's worth a seperate Issue i will start one.

**Comment by MoBosse** [comment]
@christoph4711
Could you try to set staticBorders in your config file to true?

**Comment by christoph4711** [comment]
@MoBosse

changed staticBorders to true, no visible effect...

**Comment by MoBosse** [comment]
@christoph4711

Not sure if any of these is causing your issue but:
1. Are you sure about the nameProperty: beeing NI_GJ? At a first glance it looks as if it should be "GEN"..
2. At the map-options: I think you either have to add something where it says "replace me" (tileURL, etc) or you have to delete those rows

**Comment by christoph4711** [comment]
change it ...no visible effect. but 

Using shift ctrl + I shows the follong error

TypeError: this.plugin.options.colorRange.map is not a function[Weitere Informationen]
sdg.js:2247:22
onAdd
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:2247:22
addTo
https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5:49352
addControl
https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5:49818
init
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:280:7
Plugin
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:115:5
<anonym>
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:445:39
each
https://code.jquery.com/jquery-1.12.4.min.js:2:2879
each
https://code.jquery.com/jquery-1.12.4.min.js:2:844
<anonym>
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:443:12
mapView/this.initialise
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:1264:5
indicatorView/<
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:1373:7
notify
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:512:7
indicatorModel/this.getData
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:1180:7
initialise
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:1250:5
initialise
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:1966:5
success
https://christoph4711.github.io/open-sdg-site-starter/1-5-1/:1010:11
i
https://code.jquery.com/jquery-1.12.4.min.js:2:27444
fireWith
https://code.jquery.com/jquery-1.12.4.min.js:2:28213
y
https://code.jquery.com/jquery-1.12.4.min.js:4:22719
c
https://code.jquery.com/jquery-1.12.4.min.js:4:26925

**Comment by MoBosse** [comment]
ok. One last try:
The colorRange "chroma.brewer.BuGn" was causing trouble in my repository. 
You can try replacing it by a string of color-codes eg. ["#F6E8EC", "#EED3DB", "#E5BFCA", "#DDAAB9", "#D495A8", "#CC8197", "#C46C86", "#BB5775", "#B34264", "#AA2E53","#A21942"]

**Comment by christoph4711** [comment]
@MoBosse

Sorry, but i am such a greenhorn in this whole thing. Where exactly i have to insert the list?

**Comment by MoBosse** [comment]
No problem. 
That´s what I meant. Sorry it doesn´t work.

**Comment by christoph4711** [comment]
Nevertheless inspecting the site with ctrl shif +I shows  an other error as before:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://github.com/christoph4711/open-sdg-data-starter/blob/develop/NI_GJ.geojson. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).
Error: Bounds are not valid.
leaflet.js:5:31672
fitBounds
https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5:31672
init/</<
https://christoph4711.github.io/open-sdg-site-starter/assets/js/sdg.js:419:11

**Comment by christoph4711** [comment]
in small steps it's getting better ;-)
![grafik](https://user-images.githubusercontent.com/53389268/63759818-74c63900-c8be-11e9-9d50-b970ad09251b.png)

The map is displayed now, but the colors are very grey, the circle onm the left side ist sill running...

No errors reportet in firefox "Konsole"

have a loock [here](https://christoph4711.github.io/open-sdg-site-starter/1-5-1/)

**Comment by MoBosse** [comment]
I think the circle is running because it tries to load a tile (image in the background)
Line 148 - 151 in your config file.

But it seems as if the map doesn´t get any values. Could you change noValueColor: #f0f0f0
to noValueColor: '#f0f0f0' (with ''). If the dark grey turns into light grey we are sure that there are no values.

**Comment by christoph4711** [comment]
no effect.....
I am not sure what to insert for
tileurl: 
id:
and
accessToken:

looking at the exampe of brockfanning doen't helb me in this special question....

**Comment by christoph4711** [comment]
Sorry I've ansered too fast now the map is light grey. I Think it has something to do with the gejson file conecting to the csv data.

To my mind, the values in the cvs file are conected with the map via the values in the column GeoCode

In my case this is the value AGS in the column GeoCode (specifiing a city ore region) like 03101 for Braunschweig. 

In my geojson is this value unique.

Is this right?

**Comment by MoBosse** [comment]
I Thinks that is right.
Again: are you sure about the nameProperty to be NI_GJ? When I look at your GeoJson file I see "Gen": Braunschweig, "Gen": Salzgitter etc. so I would say this is your nameProperty.

Concerning tileUrl, etc:
take a look at our [repository](https://github.com/G205SDGs/sdg-indicators/blob/develop/_config.yml)

**Comment by christoph4711** [comment]
Thank you, I will try it this evening.

**Comment by christoph4711** [comment]
Thank you @MoBosse changing name to GEN  and inserting your tileURL and access token solves the problem.

I'm not sure if I can use your access-token? To my mind the access-token has to be unique. I hope no errors occure on your site, because me and you are using the same access-token

But it really looks like the connection to the csv file don't work, but I don't have any idea, which field I schould use connecting map an csv file... 

find my config.yml [here](https://github.com/christoph4711/open-sdg-site-starter/blob/develop/_config.yml)

and my geojson [here](https://github.com/christoph4711/open-sdg-site-starter/blob/develop/assets/maps/NI_GJ.geojson)

any ideas @brockfanning

**Comment by christoph4711** [comment]
I have genereated my own access-token - perhaps this has to be added [here](https://open-sdg.readthedocs.io/en/latest/maps/)

**Comment by christoph4711** [comment]
I have created my own access-Token. May be this hint should be inetrgrated [here](https://open-sdg.readthedocs.io/en/latest/maps/)

I have also copied map options from [kazstat](https://github.com/kazstat/sdg-site-kazstat/blob/develop/_config.yml#L121) (of courcse chaning the access-token, the geojson, name and id Propertie) to my config.yml and everything works fine.

In the upper right corner of the map the min (1230) and max (813080) values from the csv are displayed correctly.

I took a look at the geojson file from kasztat and the corresponding cvs but I have no idea why it doesn't work in my case. 

[Map](https://christoph4711.github.io/open-sdg-site-starter/1-5-1/#mapview)

Files:
[config.yml](https://github.com/christoph4711/open-sdg-site-starter/blob/develop/_config.yml)
[Gesojson](https://christoph4711.github.io/open-sdg-site-starter/assets/maps/NI_GJ.geojson)
[cvs](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/data/indicator_1-5-1.csv)

**Comment by christoph4711** [comment]
I took a closer look at my geojson file. It turned out that the AGS is not unique because, there are cities consisting of two different administrative disctricts. eg in my case the one island belonges to the administrative district "Leer". In the following leer has two shapes... my colleague  is working on that.... may be this interesting for you @MoBosse too....

**Comment by MoBosse** [comment]
@christoph4711: I was just about to write you about it. I deleted the duplicate shapes but that did not solve the problem that the values from the csv are not transferred to the map. 

I ended up in replacing all idProperties from "AGS": "01" to "AGS":"code01" see here [see here](https://github.com/G205SDGs/sdg-indicators/blob/develop/assets/maps/L%C3%A4ndergrenzen_ohne_Seegrenzen.geojson). Now it works. 
Nevertheless this is kind of strange because when I used another geojson file (comeing from [here](https://hub.arcgis.com/datasets/esri-de-content::bundesl%C3%A4ndergrenzen-2016-1?geometry=-31.36%2C46.294%2C52.268%2C55.906) I had no problems to use numeric idProberties (in this case I used the "OBJECTID").

**Comment by christoph4711** [comment]
@mobosse

> I ended up in replacing all idProperties from "AGS": "01" to "AGS":"code01" see here see here. Now it works. <

This would have been the next step I tried. have look [here](https://github.com/christoph4711/open-sdg-site-starter/blob/develop/assets/maps/NI_Kurz_diss.geojson) there ist works, but the conection between geojson and the csv file dont work as you can see [here](https://christoph4711.github.io/open-sdg-site-starter/1-1-1/).

Next step I will try is to delete the "0" in the beginning of the AGS, in the geojson as well as in the csv file.... But this is almost the sam you did with entering "code" in the beginning of the AGS

**Comment by christoph4711** [comment]
@MoBosse @brockfanning

It works!  Have a look [here](https://christoph4711.github.io/open-sdg-site-starter/1-1-1/)

I am not shure why. After trying different geojson files it turned out that the identifier im my case "AGS" cant be numeric. eg "K0357" works "0357" don't. 

Now the map is colored depending on the vlaues in the cvs file.

In my case I have 4 years included. In the color explanation in the upper right of the map the "min" and "max" values come  from the whole period of the 4 years....
![grafik](https://user-images.githubusercontent.com/53389268/63943008-1be9d280-ca6f-11e9-9c3a-8567819a0ef3.png)

Moreover the city names are cutted by the values, as you can see here:
![grafik](https://user-images.githubusercontent.com/53389268/63943196-708d4d80-ca6f-11e9-9a2f-3d2cbcd38a1e.png)
