### ISSUE TITLE
Footer field for "copyright"

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#329]
Either adding a footer field for a copyright entry or making the footer fields generally configurable.

The second approach could be even better, as countries could complement what ever they want.

**Comment by brockfanning** [comment]
Just brainstorming ways to make this configurable. Maybe there could be a setting in `_config.yml` like this?
```
highlighted_metadata:
  - computation_units
  - national_geographical_coverage
  - my_custom_field
```

**Comment by brockfanning** [comment]
I'm realizing that making this configurable may be quite a heavy lift. The reason is that these footer fields are hardcoded in several places in both markup and javascript. For example see how the measurement unit is hardcoded [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/scripts.html#L51), [here](https://github.com/open-sdg/open-sdg/blob/5a5080a67cb14af5be2ddf50fde02ffd17a6229e/_includes/assets/js/indicatorModel.js#L39), [here](https://github.com/open-sdg/open-sdg/blob/5a5080a67cb14af5be2ddf50fde02ffd17a6229e/_includes/assets/js/indicatorModel.js#L183), [here](https://github.com/open-sdg/open-sdg/blob/faec9dc60ad1094038a2913d9656547701b3bb6f/_layouts/indicator.html#L59), and [here](https://github.com/open-sdg/open-sdg/blob/6992db330634edc9018205bfc8d814c728053c8f/_includes/assets/js/indicatorView.js#L379).

I'm thinking that adding a footer field for Copyright will be dramatically easier.

**Comment by brockfanning** [comment]
@MoBosse Do you have interest in giving this a try? I believe that the links in my previous comment represent the places where new code for a "Copyright" field would be needed.

**Comment by brockfanning** [comment]
@Nachhaltige-Entwicklung-Deutschland ^^^
