### ISSUE TITLE
H2 heading should depend on indicator_available

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#337]
We use a metadata field called `graph_title`, for example [here](https://github.com/open-sdg/open-sdg/blob/master/_layouts/indicator.html#L42) and [here](https://github.com/open-sdg/open-sdg/blob/master/_layouts/indicator.html#L59). Is this still needed? Can't it just be the indicator name?

**Comment by brockfanning** [comment]
@AnnCorp @LucyGwilliamAdmin I was wondering if you have any memory of the rationale for the "graph_title" metadata field. Is there any reason why we couldn't just use the indicator name instead of having a separate field for the graph title? Are there cases where the graph title would need to be different from the indicator name?

**Comment by LucyGwilliamAdmin** [comment]
I don't think I was on the team at the time so not sure where the rationale originally came from. However, indicator name can get very long so sometimes there is a need to make graph title more succinct e.g. https://sustainabledevelopment-kyrgyzstan.github.io/2-2-2/ (I know we've done some work so that text isn't squished up on one line - upgrading Kyrgyzstan soon once reporting status fixed - but still think this would go over several lines)

At the moment, graph_title appears in two places (the section header and as the graph title). One thing we have been thinking about is having the section header as "indicator_available" instead and keeping the graph title as graph_title.

Another thing which has come up a couple of times is a dynamic graph title i.e. if the units type changes the graph title would also reflect this change.

**Comment by AnnCorp** [comment]
Hi All, From memory this field was added as there were valid instances where the graph title would be different to the indicator name, particularly as Lucy says where the indicator name is long.

**Comment by brockfanning** [comment]
Thanks for the feedback @LucyGwilliamAdmin and @AnnCorp. It sounds like it's definitely needed.

I'm trying to consolidate a list of the required fields, and also re-think their names, if needed. Since it sounds like the main distinction is length, would it make sense to use something like `indicator_name_short` rather than `graph_title`? We do have a precedent with goals, where we have a regular goal name and a short goal name.

And Lucy I'm glad you bring up the double-graph-title situation we have now. Making the section header dependent on another field, like indicator_available, seems fine, as long as we're OK with making another field required. Just to rule out the obvious though, have we considered removing that section header altogether?

**Comment by LucyGwilliamAdmin** [comment]
I'm not really sure - I think `graph_title` makes it more obvious what the field is for.

Could it be customisable? Like a switch in the config file to turn it on or off as I think if it was pointing at a different field there may be more countries who want it?

**Comment by brockfanning** [comment]
Ok, I see how `graph_title` does make clear how/where it will be used in the platform. I'm hesitant to add more configuration options, unless it's something countries are already asking for. So I'm fine with leaving things as is with the graph_title field.

Should we also leave that section header alone? Or do you want to consider changing the field that determines it? Or alternatively removing it altogether?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe we decided we'd H2 (the heading just above the chart tabs) depend on the `indicator_available` metadata field. And if that field were missing, that H2 would not display. Do I have that right?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning yes, that's right

**Comment by brockfanning** [comment]
Cool, I've updated the name of the ticket.

Estimate: 1-2 hours (fairly easy task).

I think since this is a very visible change, it will require a "breaking change" entry in the changelog.
