### ISSUE TITLE
Zero as decimal place is not displayed

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#341]
![grafik](https://user-images.githubusercontent.com/50657629/63949971-77ba5880-ca7b-11e9-8297-9c6e1877a4f2.png)

I have just seen that this problem does not occur on the UK site:

![grafik](https://user-images.githubusercontent.com/50657629/63950308-062eda00-ca7c-11e9-8f6f-a28b53058eef.png)

What do I need to change?

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse I'm not sure if this is something to do with our rounding feature:
We have [this file](https://github.com/ONSdigital/sdg-indicators/blob/develop/assets/js/custom.js) in our site repo - the function rounds value to 3 significant figures.

We also needed to add [this](https://github.com/ONSdigital/sdg-indicators/commit/1dd39c99cafd7a3bc197518642350d0f0bf4ebb8#diff-aeb42283af8ef8e9da40ededd3ae2ab2) to our config file.

**Comment by MoBosse** [comment]
That works. Thank you. 

But it brings with it a new problem. Values with different numbers of digits are displayed with different number of decimal places. See example below. 
![grafik](https://user-images.githubusercontent.com/50657629/63997267-49ca2800-cafe-11e9-9703-aa9471d63eb3.png)

Using the function toFixed (shows every value with a fixed number of decimal places) instead of toPrecision would solve this, but that would cause other problems:
For big values like 123,456.00 the decimal places are of no interest. 
Other values are already rounded in the csv files (for example a value is originally 23.49 and is saved in the csv as 23. Using toFixed would displayed it as 23.00)

Best would be to have the opportunity to define for each time series with how many decimal places the values should be displayed...

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you think it would work if we had a metadata field called number_dp and then in `custom.js` for whatever function we had, we would have the number as `meta.number_dp` or would it have to be a much more technical change?

**Comment by MoBosse** [comment]
@LucyGwilliamAdmin this would only solve half of the problem, because there could be time series with very different values in one indicator (or e.g. a time series once as absolute values and once as shares of something).
I thought of something like inserting a column in the csv files with number_dp

**Comment by LucyGwilliamAdmin** [comment]
I think by default the value is what is in the csv file. If the main problem you want to fix is for the zero to not be removed when it needs to be there, maybe we should fix that instead?

**Comment by MoBosse** [comment]
Yes of course, if this is possible without using the rounding function it would be good

**Comment by LucyGwilliamAdmin** [comment]
OK, great - will take a look

**Comment by LucyGwilliamAdmin** [comment]
I think we may want to use something like this: https://www.npmjs.com/package/stringify-with-floats
@brockfanning I can't find a source url for this so I can test it out. Are we able to use `npm i stringify-with-floats` or does everything need to be in the `<script src=""..></script>` format?

**Comment by LucyGwilliamAdmin** [comment]
Actually I've just found this: https://cdn.jsdelivr.net/npm/stringify-with-floats@2.0.1/src/index.js but isn't really in the same format as other sources i.e. https://cdn.jsdelivr.net/npm/[package]@[version]/dist/[function].js

**Comment by LucyGwilliamAdmin** [comment]
Although, we need some kind of schema to tell it which values need to be forced to stay as floats (e.g. #.0/00/000/...). Since this changes this would need to be schema would need to be gotten using some sort of function. I think this might be a little complicated but I've been looking for a while and can't seem to find anything else that will fix the problem.

**Comment by brockfanning** [comment]
It sounds like it would be best if we could make the platform "smart" enough to be able to keep the same number of decimals as in the source data. I can't say for sure if that will be possible, but if there is a chance, the first step would be to make sure that the decimals "survive" the sdg-build processing. Right now it looks like they don't. As evidence I'm looking at the source CSV [here](https://github.com/G205SDGs/sdg-data/blob/develop/data/indicator_4-2-2.csv#L6) ("97.0") and the sdg-build output [here](https://g205sdgs.github.io/sdg-data/comb/4-2-2.json) (see the fourth item under "Value": "97").

Since that would need to happen in sdg-build, I've started [this issue](https://github.com/open-sdg/sdg-build/issues/48) about it.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'm seeing 97.0 in the sdg-build output:
![image](https://user-images.githubusercontent.com/43404358/64109913-96b93300-cd78-11e9-894d-db9aecc6a9a2.png)

The reason I thing it's the stringify function causing the problem as when I put `JSON.stringify({"x":5.0, "y":6.2})` in the console the output is `"{"x":5,"y":6.2}"`

**Comment by brockfanning** [comment]
Ah, my mistake. Ok, sounds like you're on the right track. If we can pinpoint where in the javascript the decimal is getting lost, hopefully we should be able to keep it.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @MoBosse do you know if this was fixed?

**Comment by MoBosse** [comment]
@LucyGwilliamAdmin @brockfanning Not as far as I know. But I still think it would be interesting

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning @SavvasStephanides is this something to get in to v1?

**Comment by MoBosse** [comment]
Hi @brockfanning, @LucyGwilliamAdmin,
I thought of solving this temporarily by doing the following:

- Defining a column called „decimal places“ in the csv files where I have values I want to be displayed with a certain number of decimal places.

- Add the „decimal places" to the list of columns that should not become a field [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/model/utils.js#L64)

- Adding a rounding function here that looks like

`opensdg.dataRoundingDecimalPlaces = function(value, dPlaces){if(value == null){
      return value}
   else{
      return value.toFixed(dPlaces)
   }
}`

**Comment by MoBosse** [comment]
..sorry posted by accident.

next step was:

- calling the opensdg.dataRoundingDecimalPlaces function [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/model/dataHelpers.js#L49) if item.decimal places is defined.

Problem is: it does not work. If the approach is as simple as I thought and I just missed something, could you please give me a hint? If it is not that simple, feel free to ignore this idea.

**Comment by brockfanning** [comment]
After some more research, I see that a "smart" approach simply isn't possible, because the way that Javascript parses JSON automatically drops the zeroes. So we need to figure out a way to add the zeroes back in afterwards.

I'm hoping we can strike a balance  - using the idea @LucyGwilliamAdmin proposed of a metadata field controlling the number of decimal places, while still allowing for particular time-series within an indicator that need different levels of precision. Hopefully this will meet the requirement without requiring a new data column (though that is also a workable idea). I'm working on a PR that would work like this.

If you want to force 1 decimal place for an indicator:

```
precision:
  - decimals: 1
```

If you want to force 1 decimal place only when the unit of measurement is "total":

```
precision:
  - unit: total
    decimals: 1
```

If you want to force 1 decimal place only when the unit of measurement is "total" and the series is "foo":

```
precision:
  - unit: total
    series: foo
    decimals: 1
```

If you want to force 1 decimal place when the unit of measurement is "total, and 2 decimals places when the series is "foo":

```
precision:
  - unit: total
    decimals: 1
  - series: foo
    decimals: 2
```

Feedback is appreciated, in particular if there is a use-case where this would not be sufficient.

**Comment by LucyGwilliamAdmin** [comment]
@emmawoodons this is something we would appreciate some thoughts on if possible, as a fix for decimal places that are zero not showing e.g. on 1.2.1:
https://sdgdata.gov.uk/1-2-1/

![image](https://user-images.githubusercontent.com/43404358/106132683-26c0ff00-615c-11eb-82b1-5db6c419f324.png)

**Comment by EmmaWoodONS** [comment]
@LucyGwilliamAdmin This looks really good, particularly with the ability to control number of dp based on units: The example you sent for 1.5.1 is fine for Units=Rate, but doesn't work for Units=Deaths, but it looks like the unit control will fix this. Would we be able to control it based on both series and units ?
