### ISSUE TITLE
Problem during the production merging process

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#355]
I merged the "develop" and "master" branches, but the name of national indicators is not shown
http://sdg.armstat.am/1/

**Comment by brockfanning** [comment]
@SDGArmenia I believe the problem is a version mismatch between the `_config.yml` and the `_config_prod.yml`. A simple fix might be to make sure that `_config_prod.yml` is using the same versions of open-sdg and sdg-translations as `_config.yml`. A better fix, though, would be to change the deployment script so that `_config_prod.yml` only needs to contain the differences, rather than everything.

It's tough to describe that, so I'll put up a pull-request to demonstrate what I'm talking about.

**Comment by brockfanning** [comment]
@SDGArmenia I've put up a pull-request that demonstrates this - though I also took the opportunity to upgrade to the latest versions of open-sdg, sdg-translations, and jekyll-open-sdg-plugins. I would recommend merging [this pull-request](https://github.com/armstat/sdg-site-armenia/pull/68).

But for reference, as for the "better fix" I mentioned before, that is demonstrated by these two commits:
1. Change the CircleCI config so that both _config.yml and _config_prod.yml are used when building production ([see here for reference](https://github.com/armstat/sdg-site-armenia/pull/68/commits/fbc2a5dbd52925735762f5bbdd97986a12b1fdee))
2. Update _config_prod.yml so that it only contains the differences from _config.yml ([see here for reference](https://github.com/armstat/sdg-site-armenia/pull/68/commits/9b1328c3dbaac13d25f61029d3590817f6f5c2a4))

**Comment by brockfanning** [comment]
Cleaning up the queue a bit - I think this can be closed. Please re-open if needed.
