### ISSUE TITLE
Proxy tags improvement

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#373]
Maybe we could make the following improvements to tags:
1. Tags don't split over several lines
2. Stop tags on second line from overlapping

![image](https://user-images.githubusercontent.com/43404358/65602554-fb446800-df9b-11e9-9509-37e211f14b67.png)

**Comment by brockfanning** [comment]
Yes, I think both of those things can be accomplished with a change to default.scss. The wrapping problem would probably involve the [white-space: no-wrap](https://www.w3schools.com/cssref/pr_text_white-space.asp) rule. The overlap problem probably with either `line-height` or maybe `margin-bottom`?

**Comment by brockfanning** [comment]
@phillipgardiner This ticket already existed.

**Comment by phillipgardiner** [comment]
@brockfanning In additional to the above, we would like to change the styling on the orange tags to match the 'reported online' and 'exploring data sources' tags on the goal page. In order to do this please use the following:

background colour: #F0AD4E (i'm going to assume that we stick with the orange for now)
text colour: black. #0B0C0C seems to be the black we use for text etc
font size: 12px
Currently the text in the tag is a link. Please remove this ability as it just links to the same place as clicking the indicator text.
I'm going to assume you can get all the padding etc from the goals page tags.

Essentially they just need to look like the existing 'reported online' and 'exploring data sources'

@brockfanning do you believe I have missed anything or is that enough info to progress?
