### ISSUE TITLE
Too many metadata tabs break mobile site

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#381]
Example:
![image](https://user-images.githubusercontent.com/43404358/67003275-81ecf080-f0d5-11e9-99ac-06bbcb691b27.png)

@SavvasStephanides suggested maybe we could have a moving horizontal bar 
Will try to find example

**Comment by brockfanning** [comment]
Just pointing out one possible example, the [BBC News](https://www.bbc.com/news) page has a lot of horizontal navigation, both above and below the header. Above the header, they're dumping the excess items into a "More" dropdown. Slightly different approach, on the [Sport](https://www.bbc.com/sport) page, below the header, they're letting the excess items get hidden, but also showing an "All Sport" drop-down that has everything. Seems like their design goals included:
1. No horizontal scrolling
2. Keep the navigation on one line

**Comment by phillipgardiner** [comment]
Just adding here as a point of reference. https://design-system.service.gov.uk/components/tabs/default/index.html#past-day. Example shows how once reaches a certain size the layout changes to links and displaying to the content of the tab in full. They also have the code of this page if re-usable?

**Comment by brockfanning** [comment]
I really like that approach, and I think that kind of simplicity is ideal.

From the technical perspective, it seems like that should be easy - really just to telling Bootstrap 3 not to process those tabs on mobile.

But I wouldn't be surprised if it turned out hard to do that. I don't have much Bootstrap experience.

One consideration to keep in the back of our minds is that we're not currently on the most recent version of Bootstrap.

In the meantime I'd be happy if we could do that links approach. If it turns out to be tough, we could pile on yet another JavaScript library: https://www.jqueryscript.net/layout/Mobile-Friendly-Bootstrap-Tabs-Enhancement-with-jQuery.html

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning I won't make new issue for tabs as this one pretty much covers what's been discussed for #970

**Comment by brockfanning** [comment]
Should we close this? Currently on mobile the tabs expand to full width, ensuring that they will not wrap weirdly.

There's still the potential for weird wrapping on desktop though, in the case where there are so many tabs -- or the tab text is so long -- that it wraps even on desktop.

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Not sure. Are we saying we are no longer looking to implement the GDS approach (as referenced above) or is that captured on a different ticket?

**Comment by brockfanning** [comment]
I don't think that's captured in any other tickets. I'm open to discussion on the GDS approach. I think we've dealt with what this ticket was about -- the wrapping issues on mobile -- but that doesn't mean the UX couldn't still be improved.

**Comment by brockfanning** [comment]
We can close this issue but continue this work in #1054.
