### ISSUE TITLE
Error on Kyrgyzstan reporting status page

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#389]
Metadata terms are coming up instead of translation on staging site:
https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/reporting-status/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe this is because some "safety code" is not in the new object-oriented sdg-build workflow. This safety code used to ensure each status type had a "translation_key". To confirm that I'd recommend explicitly adding translation_key to their _prose.yml file. Here's an example in the UK repo: https://github.com/ONSdigital/sdg-data/blob/develop/_prose.yml#L143

**Comment by LucyGwilliamAdmin** [comment]
I've made that change to Kyrgyzstan's _prose.yml file but still not right:
https://github.com/sdg-kyrgyzstan/open-sdg-data-starter/blob/develop/_prose.yml#L138

**Comment by brockfanning** [comment]
Ok, sorry for the wild goose chase - I think this means it is a bug in sdg-build, probably either in [this file](https://github.com/open-sdg/sdg-build/blob/master/sdg/schemas/SchemaInputOpenSdg.py) or [this file](https://github.com/open-sdg/sdg-build/blob/master/sdg/schemas/SchemaInputBase.py), something related to "translation_key".

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning 
No problem at all!
Might be completely wrong but could it be [line 102 here](https://github.com/open-sdg/sdg-build/blob/master/sdg/schemas/SchemaInputOpenSdg.py#L102)
Maybe `if 'translation_key' not in prose_field['options']` instead of `if 'translation_key' not in prose_option`

**Comment by LucyGwilliamAdmin** [comment]
Changing just that didn't work

**Comment by LucyGwilliamAdmin** [comment]
Closing this as issue was fixed
