### ISSUE TITLE
Hyperlinks colour and style (site wide) 

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#628]
From expert review.
Hyperlinks to be blue and underlined
Visited and unvisited states to be different colour

**Comment by phillipgardiner** [comment]
GDS say..[https://design-system.service.gov.uk/styles/typography/] 3/4 of way down page

Links are blue and underlined by default. If your link is at the end of a sentence or paragraph, make sure that the linked text does not include the full stop.
Only remove underlines from links if the number or placement of links makes them difficult to scan or interact with the element they’re part of, and it’s clear to the user from the context that they’re links, even without the underline
For example, navigation links in a header won’t necessarily need underlines. Users will understand that they’re links because of their position on the page.

Link colours to be used can be found here: https://design-system.service.gov.uk/styles/colour/

**Comment by phillipgardiner** [comment]
I've been looking at this a little more in regard to 'only remove underlines from links if the number or placement of links makes them difficult to scan or interact with the element they’re part of, and it’s clear to the user from the context that they’re links, even without the underline'

Bearing the above in mind I believe that all links should be blue and underlined apart from the following:
- The navigation links in both the top and bottom navigation menus
- Search results

**Comment by brockfanning** [comment]
@phillipgardiner I think this is mostly done. Though, on the search results page, the links still aren't underlined. Should be fix that?

**Comment by phillipgardiner** [comment]
@brockfanning no need to underline on search results (see comments above) :)

**Comment by AnnCorp** [comment]
@brockfanning @phillipgardiner can this ticket be closed?

**Comment by brockfanning** [comment]
Yes, it sounds that way. Closing now.
