### ISSUE TITLE
Add configurable text for goal page

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#631]

**Comment by brockfanning** [comment]
@AnnCorp @LucyGwilliamAdmin A question to answer before implementing this is: would it be better for the goal page text to be managed in the data repository or the site repository?

**Comment by AnnCorp** [comment]
@brockfanning What would be the advantages or disadvantages of each? Also which repositories are text in other pages managed in eg home page?

**Comment by brockfanning** [comment]
@AnnCorp To your second question - it's sort of a mixture. These bits are managed in the site repository:

* Home page intro
* Page content ("About", "FAQ", etc)

And these are managed in the data repository:

* Indicator metadata
* Indicator content (the blurb that displays at the top)

To your first question - I hadn't really thought it through before, but I think it boils down to this: Is it required for this goal content to be available via a machine-readable endpoint, like our indicator metadata and data are? Or would it be sufficient for this goal content to be purely for display on the open-sdg platform?

My thinking is, if it's the former -- machine-readable goal content -- then it needs to be on the data repository. Otherwise it should be on the site repository.

**Comment by AnnCorp** [comment]
@brockfanning thanks for clarifying. I think Goal page intro text more logically sits in the family with Home page and Page content, so therefore would sit in site repo.
@LucyGwilliamAdmin what do you think?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning agree - think it makes sense for it to go in site repo

**Comment by phillipgardiner** [comment]
@brockfanning has this one been done already?

**Comment by brockfanning** [comment]
@phillipgardiner Sorry, missed your question - no I don't believe so.
