### ISSUE TITLE
Add single column version of goal page with targets

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#633]
see Phill's mockup

**Comment by phillipgardiner** [comment]
Example mockup

![image](https://user-images.githubusercontent.com/60919820/79485922-e00b7980-800d-11ea-9827-385798b18250.png)

**Comment by brockfanning** [comment]
Tech note: We already have a [goal-by-target layout](https://github.com/open-sdg/open-sdg/blob/master/_layouts/goal-by-target.html), so we might call this one "goal-by-target-vertical".

**Comment by phillipgardiner** [comment]
Reasoning behind the requirement for this design is users have previously stated that using the current layout it is very hard to clearly see the relationship between between goals and their indicators. This is especially true on mobile layout where the two columns become merged. Additionally the current layout if fairly cluttered and does not support scanning the text of the page. It is envisaged that the above design becomes another options for Open SDG developers that can can be chosen to be turned on or off.

**Comment by brockfanning** [comment]
@phillipgardiner What are you thinking for the text sizes? Specifically, should the various sections be h2, h3, normal text, etc? The three sections I'm wondering about are:
1. The "Targets and Indicators" header
2. The target names (eg, "1.1 By 2030, eradicate extreme poverty for all people everywhere...")
3. The indicator names (eg, "1.1.1 Reported online Proportion of population below the international...")

**Comment by phillipgardiner** [comment]
@brockfanning Fair point, this doc probably needs a bit of additional annotations as it was done a while back as a concept, but things like fonts have moved on since then. I would say in regard to your comment:
1. H2
2. To be honest i'm not 100% sure about this one. I think H3 is going to be a bit big and normal text 16px may be too similar to the indicator size. I think it will either have to be normal copy Or we introduce a H4 19/20px specially for this. I'd really like to see both options if possible to be able to make a call on it. Perhaps we start with it at normal text and then adjust as necessary.
3. Normal copy text 16px

Thoughts?

**Comment by brockfanning** [comment]
@phillipgardiner Here's a rough draft for feedback:
![screenshot-127 0 0 1_4000-2020 07 14-11_45_49](https://user-images.githubusercontent.com/1319083/87446725-aaa00900-c5c7-11ea-9060-00a52341d0a0.png)

**Comment by phillipgardiner** [comment]
@brockfanning Thank you. I think given that the indicators will be blue and underlined this will act as enough of a differentiation when a user scans a page to pick out what are targets and what are indicators. You'll hate me for saying it but with all things we can iterate (if required) so I would propose sticking to normal copy for now until usability testing / user feedback says otherwise. So in summary:

1. H2
2 and 3 Normal copy text 16px

Happy to discuss though if you have strong thoughts otherwise.

**Comment by brockfanning** [comment]
@phillipgardiner No prob at all, in fact that's exactly how I had it in that screenshot. :) Any other feedback on the screenshot, apart from text sizes?

**Comment by phillipgardiner** [comment]
@brockfanning not really, only that its looking good and to point out the horizontal lines in the mock up between each target - this is to help separate each target. I'm not 100 sure if these are required or not now? I think if we do have them they should be very subtle, so the same grey as being used on the homepage links, but probably only 1px thick and probably centre justified not going to the edges of the page (so they don't chop up the page). I can mock something up to show what I mean, but it will have to be tomorrow as need to log off now. Good work :)

**Comment by brockfanning** [comment]
Cool, here's an update with that horizontal rule. I used the same color we use for "indicator content".

Apart from any more feedback, the only task left is to translate "Targets and indicators".

![screenshot-127 0 0 1_4000-2020 07 14-13_34_34](https://user-images.githubusercontent.com/1319083/87457817-01610f00-c5d7-11ea-9a6a-2ad94562a40d.png)

**Comment by phillipgardiner** [comment]
@brockfanning This is looking good :)

One additional thought is I wonder if we should make the horizontal lines configurable? E.g you are able to choose the colour. I remember you saying that Germany were keen to keep the colour for each goal. On the current site, on these pages, the colour of the line changes to match the goal colour. Perhaps we should continue with that idea here? This would also be similar to our homepage approach where the default is lightgrey but they can set the colour of the horizontal lines if they so wish. This isn't necessarily required for the UK site but i'm thinking of the wider audience. 

I've never noticed those lines on the indicators page before! But could we make the default colour of any of these sort of lines lightgrey please? I would like to make everything consistent and we currently use lightgrey on the homepage, reporting status page etc. This may mean I need to raise an additional card to change the indicator content to use lightgrey too.

**Comment by brockfanning** [comment]
@phillipgardiner I believe I switched it to use the default color, but it is using a "Sass variable", which makes it fairly easy for countries to override it. The mechanism for controlling these line colors makes a bit more sense as CSS, rather than configuration, which is what we are using for the alternate frontpage cards. So I'm inclined to rely on countries to use CSS if they want to override these line colors per goal - at least for now.

We can move discussion over to the PR: #776
