### ISSUE TITLE
Add configurable home page

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#634]
So doesn't just start with the goals page. See Phill's mockup.

**Comment by phillipgardiner** [comment]
Example homepage

![image](https://user-images.githubusercontent.com/60919820/79485784-b3576200-800d-11ea-9581-bc78a8647979.png)

**Comment by phillipgardiner** [comment]
When implemented this goes alongside adding a 'Home' link to the main navigation on every page apart from the homepage itself.

**Comment by AnnCorp** [comment]
@SavvasStephanides one for you to start please as discussed at Tech call.

**Comment by phillipgardiner** [comment]
@SavvasStephanides I have updated the homepage, hopefully with all the information you will need I have also demonstrated what the goals page should now look like. Happy to have a conversation this afternoon to allow you to crack on over my non-working days.
[SDG_Homepage_v2_.pdf](https://github.com/open-sdg/open-sdg/files/4831741/SDG_Homepage_v2_.pdf)

**Comment by SavvasStephanides** [comment]
Thanks @phillipgardiner. Here's what I got so far: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/new_homepage/landing/

**Comment by phillipgardiner** [comment]
@SavvasStephanides looking good, i'm just sending you over some comments in slack :)

**Comment by phillipgardiner** [comment]
Slightly updated mock up of the website to reflect techcall discussion. Changes primarily 1) Title not being links 2) Change order of 'useful resources' and 'Publications'. Thought I'd better reflect all changes to make the handover easier.

[SDG_Homepage_v2Left_.pdf](https://github.com/open-sdg/open-sdg/files/4857616/SDG_Homepage_v2Left_.pdf)

**Comment by SavvasStephanides** [comment]
# Progress so far

We've been experimenting with creating a new landing page from @phillipgardiner's mockups and feedback and this is what we have so far:

![image](https://user-images.githubusercontent.com/478770/86256011-b941f580-bbaf-11ea-9ebe-3202a8951da6.png)

## Basic features:

* The introduction banner moved from the current home page
* The goals grid with images slightly smaller than the current home page (which will become the "goals" page)
* A "Sections" row under the goals.

## Code

* The code for the new home page is located at the [`new_homepage2`](https://github.com/open-sdg/open-sdg/tree/new_homepage2) branch in `open-sdg`. 
* The landing page layout is located [here](https://github.com/open-sdg/open-sdg/blob/new_homepage2/_layouts/landing.html)
* Also made a [`home.md`](https://github.com/open-sdg/open-sdg/blob/new_homepage2/tests/site/_pages/home.md) file in the test files which implements the `landing` layout. The page can be accessed by appending `/landing` as the URL.

## Homepage sections customisability

Since our tech call, I have been experimenting with customising the sections row.

The sections are to be completely optional and customisable. To implement these, the `_config.yml` would be updated as follows:

```yml
frontpage_sections:
  sections:
    - title: Download all data
      component: download-all-data.html
    - title: Publications
      component: publications_section.html
    - title: Text section
      underline_color: "#fcc30b"
      component: resources_section.html
```

For each section:
* `title` is a required field. This would be the heading of the section
* `component` is a required field. This is a `.html` file located in the `components` directory which will be displayed under the heading.
* `underline_color` is an optional field. This will set the underline color of the heading. If it's not specified, the line will default to `#4c9f38`.

The above `yaml` would look like this on the homepage:

![image](https://user-images.githubusercontent.com/478770/86259245-b3e6aa00-bbb3-11ea-9877-40518db663a8.png)

Any feedback welcome. @phillipgardiner @brockfanning @AnnCorp

**Comment by phillipgardiner** [comment]
@SavvasStephanides only a minor thing but would you better defaulting line colours to something like black or grey? so at least it looks OK even if they decide not to change the colours.

**Comment by SavvasStephanides** [comment]
@phillipgardiner Good point. I've set it to `darkgrey`. 

![image](https://user-images.githubusercontent.com/478770/86262858-53a63700-bbb8-11ea-9b09-d703348b106f.png)

**Comment by AnnCorp** [comment]
@SavvasStephanides  @phillipgardiner really exciting that we're progressing getting a home page! Agree this look better as grey, though am struggling a bit with the lines (particularly the one under 17 goals) as they feel like they're cutting up the page in the wrong place. Lets discuss at catchup tmrw Phill and add summary here re what we discuss.

**Comment by phillipgardiner** [comment]
@AnnCorp @SavvasStephanides For the UK site. If we get the copy right, we could potentially drop the red line (see example). Happy to discuss on call.

![Screenshot (23)](https://user-images.githubusercontent.com/60919820/86336048-34a2b600-bc47-11ea-9c0b-07e7265a4131.png)

**Comment by SavvasStephanides** [comment]
@phillipgardiner I kinda like the "The 17 goals" header personally.

**Comment by AnnCorp** [comment]
@SavvasStephanides  have just talked through some tweaks with @phillipgardiner and he will do another mockup and share this as soon as poss today.

**Comment by phillipgardiner** [comment]
Hey all. Had a chat with @AnnCorp Ann earlier and listening to all feedback have come up with a slightly changed design for the homepage. Essentially the primary changes are:
- section lines have been change to able the titles (inline with GDS standard)
- section lines are to be light grey (not different colours)
- content tweaks - the content now shown is the content to be used (Useful resources links and Publications withstanding) 

[SDG_Homepage_v3Left_.pdf](https://github.com/open-sdg/open-sdg/files/4864924/SDG_Homepage_v3Left_.pdf)

**Comment by SavvasStephanides** [comment]
Thanks @phillipgardiner. Would you advise against setting the lines to different colours?

**Comment by phillipgardiner** [comment]
@SavvasStephanides I think Open SDG should have the ability too. But after conversations with @AnnCorp today, for the UK we will be starting with lightgrey.

**Comment by brockfanning** [comment]
One thing nagging at me is that this new homepage seems to have everything that the current homepage (what we're calling the "goals page") has and more. The only thing this new page "lacks" is the larger goal icons. I'm wondering if that's enough of a difference to warrant an additional page. Or instead, should this new page actually replace the "goals" page?

**Comment by SavvasStephanides** [comment]
@brockfanning The goals page is going to have to change. The introduction banner is going to be removed and replaced with a new paragraph specific to the goals page (see Phill's mockup). The only things the goals page will contain are its own paragraph and the goals tiles only larger.

**Comment by phillipgardiner** [comment]
Also the homepage has 3 additional sections, which the UK will use for Publications and Useful resources etc, but will be customisable by countries. The homepage is essentially a jumping off point. We have to remember this is version 1.0 of a homepage, it will get iterated and changes / additions will be made over time (as well as to the goals page) which will move them further away from each other in the way they look and the information they provide.

**Comment by brockfanning** [comment]
Ok, that makes sense.

Do you think we could allow countries to put more than 3 additional sections? It might be nice to have it be unlimited sections in rows of 3.

**Comment by phillipgardiner** [comment]
@brockfanning Yes that would be good if we could. There is no reason to limit it other than the amount of technical effort to achieve that.

**Comment by brockfanning** [comment]
In terms of configuration of these sections (cards?), here is mockup example of what I was thinking it might look like. The following would display four cards: bulk download, userful resources, publications, and a call-to-action.
```
frontpage_cards:
  - title: Download all data
    feature: bulk_download
  - title: Useful resources
    content: ->
      * First resource
      * Second resource
      * etc...
  - title: Publications
    content: ->
      * First publication
      * Second publication
      * etc...
  - title: Some call-to-action
    content: A brief sentence about this call-to-action...
    button_title: My call to action
    button_link: https://example.com
```

My thinking is:
1. Countries have complete control over the order/content of the cards
2. Most cards will have a "title" and "content" sections.
3. For anything that has "baked in" functionality, like the bulk download, the country just specifies "feature". This is why the "Download all data" card above does not need a "content" section.
4. Optionally a country can add "button_title" and "button_link" to display a consistently-styled call-to-action button at the bottom of the card.

@phillipgardiner I was going to ask your input on the button idea. I am guessing that it would like exactly like the bulk download button, right? Any concerns?

**Comment by brockfanning** [comment]
(I remembered there was already a config example detailed above - which has other useful stuff like the underline color. Assume we'll have that too.)

**Comment by phillipgardiner** [comment]
@brockfanning all sounds sensible to me. Yes keep the buttons the same style (for now). Side note: I have just noticed the button label is now blue? has this changed since the hyperlinks changes were brought in? It should have remain white.

In regards to colour yes the underline colour would stay. I don't know what level of customisation we are thinking but it may be worth like with the underlines, having a default grey button / darker grey when hoover, then allowing builders to change the colour to suit their style?
