### ISSUE TITLE
Change default font

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#640]
Change font to use Helvetica or Arial inline with both GDS and ONS.
High priority issue raised by Phill.

**Comment by phillipgardiner** [comment]
GDS...You should use an alternative typeface like Helvetica or Arial for services that are publicly available on different domains: [https://design-system.service.gov.uk/styles/typography/](url)

ONS website seems to use: Open Sans",Helvetica,Arial,sans-serif;

**Comment by phillipgardiner** [comment]
@SavvasStephanides how many H levels do we need? H1, H2, H3, H4????

From what I can work out based on GDS guidelines, https://design-system.service.gov.uk/styles/typography/

I would suggest:
H1 = 36px
H2 = 24px
H3 = 19px
Normal copy text 15px

**Comment by SavvasStephanides** [comment]
@phillipgardiner The lowest I've seen is `H5` on the [Updates](https://open-sdg.github.io/open-sdg-site-starter/news/) page, but I think these should change. It jumps from `H2` straight to `H5`.

**Comment by brockfanning** [comment]
@phillipgardiner Just want to clarify - is the suggestion to use `'Open Sans',Helvetica,Arial,sans-serif;` or `Helvetica,Arial,sans-serif;`?

**Comment by phillipgardiner** [comment]
@brockfanning Sorry bit ignorant here but I don't actually know what 'Open Sans' is? Is it a specific font?

Our guidelines are: "You should use a typeface like Helvetica or Arial for services that are publicly available on different domains". I'm guessing therefore it would be the latter option?

**Comment by brockfanning** [comment]
@phillipgardiner Yes Open Sans is a specific font (info [here](https://en.wikipedia.org/wiki/Open_Sans)).

Quick primer on how browsers interpret "font families": If a browser sees a list of fonts in a "font-family", it will try to use them in that order, depending on whether the font exists on the user's computer. For example, if a browser sees `font-family: Helvetica, Arial, sans-serif` it interprets that as:
1. Use Helvetica if available
2. Otherwise use Arial if available
3. Otherwise use any sans-serif font

Right now Open SDG has a font-family of `'Open Sans', sans-serif`, which means it has no fallbacks - in other words it goes straight from Open Sans to any sans-serif. So one improvement might be to add Helvetica and Arial as fallbacks, ie: `'Open Sans', Helvetica, Arial, sans-serif` (which is what https://www.ons.gov.uk uses). The change being considered at #659 removes Open Sans and changes to `Arial, Helvetica, sans-serif`.

The GDS recommendation says to use a font "like" Helvetica or Arial, and so I want to make sure that we're not changing something unnecessarily. If Open Sans is actually OK to use, and we don't have a reason to change, we may want to stick with it, but add Helvetica and Arial as fallbacks. But if there are some complaints about Open Sans, I'm fine with changing.

**Comment by phillipgardiner** [comment]
@brockfanning thanks for the above, useful :), So Open sans is a font in itself rather than a group of fonts then. I'm sold. We don't currently have a specific reason to change other than the guidelines. I did notice in places on current UK site 'Roboto' is also used (think I spotted it on the description paragraphs (page-content) used on some indicator pages) so i'm keen to just get consistency across the website. Would be happy if we could go with your second option of 'Open Sans', Helvetica, Arial, sans-serif' seeing as this is what ONS also use and it is very similar to both Helvetica and Arial. 

I don't know what the impact of this would be on the work already undertaken by @SavvasStephanides 

Ultimately I think @AnnCorp would have final say but i'm happy with what you propose :)

**Comment by SavvasStephanides** [comment]
@phillipgardiner The work I'm doing right now removes the 'Open Sans' font entirely, instead going for Helvetica and Arial. If you prefer to include Open Sans, I'd be happy to do it in the ticket I'm working on.

**Comment by phillipgardiner** [comment]
@SavvasStephanides @brockfanning it sounds like Brock has sound reasons to keep it in, and I don't have any strong reason to remove it. So let's keep it for now until we potentially have any evidence in the future that its not working as a font (which I very much doubt will happen). So to confirm we go with 'Open Sans', Helvetica, Arial, sans-serif - both agree?

**Comment by brockfanning** [comment]
Agreed, sounds good.

**Comment by SavvasStephanides** [comment]
Sounds good. I'll implement the change in my headings ticket.

**Comment by AnnCorp** [comment]
Sounds good to me too - thanks all.

**Comment by SavvasStephanides** [comment]
@AnnCorp @brockfanning @phillipgardiner I think we can close this as it has been implemented in the headings ticket.

**Comment by LucyGwilliamAdmin** [comment]
This was fixed in #659
