### ISSUE TITLE
Not able to configurate languages 1.0.0

### ISSUE THREAD

**Issue by mgbernal** [open-sdg/open-sdg#644]
When trying to configure any other language appart fom english, trying to configure an open-sdg side @ 1.0.0 from scratch following quistart guide, when  testing site  configuration file, always receive:
"/ods-site-madrid/en

` internally linking to /ods-site-madrid/en/about/cookies-and-privacy/, which does not exist (line 0)
     <a href="/ods-site-madrid/en/about/cookies-and-privacy/">Cookies</a>`
...
`htmlproofer 3.15.2 | Error:  HTML-Proofer found 1343 failures!
`
Any clue what could be happenning?
Thanks for your help

**Comment by brockfanning** [comment]
@mgbernal The automated "html proofer" test crawls the entire site and looks for any broken links. If you add a language, you've got to create new versions of all the pages in the `_pages` folder, and posts in the `_posts` folder.

There's a [Python script to help](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/scripts/batch/add_language.py), but really all that it's doing is created copies of all the pages and posts in the new language. You can also do this manually if preferred.

Also, feel free to delete any pages or posts you don't need. That will make it easier because then you won't have to create new versions of them.

**Comment by mgbernal** [comment]
@brockfanning Thanks, it is working as expected :) Now we are online in Madrid
Thanks for your quick help

**Comment by brockfanning** [comment]
@mgbernal 

On 17th June at 13:00-14:30 UK time (GMT+1), the UK Office for National Statistics (ONS), the UN Statistics Division (UNSD), and the Center for Open Data Enterprise (CODE) will be holding a webinar for users of Open SDG.

The webinar will:
* present new developments and key features of Open SDG
* discuss questions and features from countries
* help create a community of users of Open SDG
 
[A draft agenda is available here](https://github.com/open-sdg/open-sdg/blob/news-events-docs/docs/Open-SDG-Webinar-Agenda.pdf?raw=1).

Please register your interest and send your questions to [Lucy Gwilliam](mailto:Lucy.Gwilliam@ons.gov.uk) by June 3rd 2020.

Best regards,

Brock
