### ISSUE TITLE
search_index_extra_fields doesn't seem to work

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#692]
In UK, we have a field in our metadata called data_keywords and when I [search for “smoking” on UK live site](https://sustainabledevelopment-uk.github.io/search/?q=smoking), a result was returned as smoking was set in the data_keywords field.
However I’ve added the following to the config for the test site and the result isn’t being returned when I [search for smoking on the UK test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/search/?q=smoking).
```
search_index_extra_fields:
  - data_keywords
```

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I don't think "smoking" is in the keywords anymore, is it? I did notice that if I search for "crime", that 16-2-1 shows in the results. And since "Crime" only shows up in the keywords for 16-2-1 (see the [metadata for 16-2-1](https://raw.githubusercontent.com/ONSdigital/sdg-data/36b764381c44c6a4e4dee3bc017a5b3f5ca50000/meta/16-2-1.md)), that makes me think it's working as intended.

**Comment by LucyGwilliamAdmin** [comment]
Ok, great, just added smoking back in to the one in the example and is working. Closing
