### ISSUE TITLE
Download chart as image

### ISSUE THREAD

**Issue by dougmet** [open-sdg/open-sdg#73]
This was an issue that was nearly resolved on the UK site with PR ONSdigital/sdg-indicators#2591 . As I'm closing the PR there I wanted to keep a link open to the code - even if we then close this issue.

The feature was for a user to be able to click a button and download an image of the chart they had been producing.

The reason the UK PR never got merged was that the legend was not on the chart because it had been generated outside of the chartjs. The code for downloading the rest of the image was completed however in that PR.

**Comment by brockfanning** [comment]
It would be great if we could figure out how to include HTML elements in the downloaded image. This would let us include the legend, and would also allow us remove the duplicative"graph_title".

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've done some research into this and have figured out how to get the legend to be in the downloaded chart image - see branch (legend-in-chart-download). This isn't perfect:
- currently doesn't work on edge or IE due to errors.
- when the file does download in Chrome, it is downloaded without an extension.
- the js functions come from GitHub (and look as if they are not really being developed) - might be best for us to take a look at them and create our own functions. This way we could also try to fix the two above issues.

What are your thoughts?

**Comment by brockfanning** [comment]
I really like the sound of this. We might even be able to leverage this to allow the other text on the chart (like the graph title and footer fields) to be HTML instead of canvas.

**Comment by LucyGwilliamAdmin** [comment]
Yeah, that could work - I'll take a look into it
