### ISSUE TITLE
Upper / lower case: Language specific

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#752]
**Please complete the following information** 
Site repository URL: https://g205sdgs.github.io/sdg-indicators//reporting-status/
Open SDG version: 1.0.0

**Describe the bug**
Not sure if this concerns other countries too but nouns are generally capitalized in German. So e.g. [here ](https://g205sdgs.github.io/sdg-indicators//reporting-status/) the "244 indikatoren" should actually be written with a capital "I".

**Expected behavior**
Depending on the selected language, it should be decided whether a word should be downcasen( e.g [here](https://github.com/open-sdg/open-sdg/blob/master/_layouts/reportingstatus.html#L4-L5)).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50657629/85283823-4b4e4d80-b48e-11ea-953e-588bb0b55f96.png)

**Comment by brockfanning** [comment]
I believe the only way to handle this would be to have a translation with a variable in it, like [here](https://github.com/open-sdg/sdg-translations/blob/master/translations/en/indicator.yml#L4). Maybe something like:

`num_indicators: %num indicators`

Then the German could be:

`num_indicators: %num Indikatoren`

And the layout code would need to be something like:

`<span>{{ page.t.indicator.num_indicators | replace '%num', overall.totals.total }}</span>`

Unfortunately there's a gotcha because we have a `<span>` around the number in our markup. So the translation would actually need to contain some HTML, like:

`num_indicators: <span class="total">%num</span> Indikatoren`

**Comment by MoBosse** [comment]
After some research I found out that there is a general substantive capitalization besides in German only in Luxembourgish.
Apart from that, the example on the reporting status page seems to be the only case where this problem occurs, so I'm going to solve this by overwriting it in our code and close the issue.
