### ISSUE TITLE
Generate disaggregation status

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#794]
Following on from the addition of the disaggregated report, we want to  automatically generate indicator 17.18.1:
Proportion of sustainable development indicators produced at the national level with full disaggregation when relevant to the target, in accordance with the Fundamental Principles of Official Statistics

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just added this issue to 1.2.0 but we can discuss at next week's tech call if something needs to come out

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp Do you think that 17.18.1 should be a time-series chart, like all the other indicators, so that it shows progress over the years? Or should it be different from all the other indicators, and only show the current percentage?

I've been assuming that it should be a time-series, which means that this can't be 100% automated. In that case, it would be up to the country to maintain the percentages in a CSV like any other indicator. But we can help the country by providing, along with the disaggregation report, a percentage representing the current state. Then once a year, the country can take that percentage and manually add it to their CSV for 17.18.1.

On the other hand, if 17.18.1 should be different from the other indicators, and display only a single percentage showing the current state (ie, no time series), then it is possible to 100% automate it.

**Comment by AnnCorp** [comment]
@brockfanning @LucyGwilliamAdmin my thoughts are that there is a need for both an autogenerated latest picture (like we have for reporting status) but also for a timeseries for 17.18.1 to show progress over time. Could we do this in some way with series options? Or actually should we have 17.18.1 with just a time series controlled by countries and then a separate disaggregation reporting page, either additional to or built into reporting status?

**Comment by brockfanning** [comment]
I'm not sure offhand how it could be done with the series options. But I'm in agreement with your thought of doing both the time series and the autogenerated latest picture. Personally I prefer your idea of adding the autogenerated latest picture to the reporting status page.

**Comment by brockfanning** [comment]
@AnnCorp @LucyGwilliamAdmin @phillipgardiner @jwestw 
Since this task will involve enhancements to sdg-build in order to accommodate the changes here, I am thinking that we should start with a mockup, to avoid wasted effort. So my first question is: how should the reporting status page change?

I can imagine a couple of alternatives:
1. A new line at the top (or bottom) of the page that says, for example, "Percentage of indicators that are fully disaggregated: 35%".
2. A new line below each of the 17 goals that says, for example, "Percentage of indicators in Goal 7 that are fully disaggregated: 35%". And presumably if the page is using the "extra fields" (like "Status by tier", for example) then a similar line would appear below each of these (eg, "Percentage of tier 1 indicators that are fully disaggregated: 35%).

Also here's a visual question for either of these alternatives: should this be another horizontal bar chart? Or just the percentage written as text?

In terms of level of effort, here is a really rough estimate of the four combinations:
* Single percentage, plain text: 5-10 hours
* Single percentage, bar chart: 8-13 hours
* Percentages by goal/field, plain text: 15-20 hours
* Percentages by goal/field, bar charts: 20-25 hours

Lastly, does my approach of "Percentage of indicators" above make sense? Or does the percentage need to be more granular? For example, if an indicator has 9 of the 10 required disaggregations, then technically it is not "fully disaggregated" - but do the numbers need to reflect that it is _almost_ fully disaggregated?

**Comment by AnnCorp** [comment]
@brockfanning @phillipgardiner @LucyGwilliamAdmin I think bar over plain text for consistency but will have to make sure the purpose of each of the bars is clear to users. For headline data reporting status, we have the overall summary and a figures for each goal (or other customised view) so I think we ultimately should aim to replicate that for disaggregations, but could do iteratively and start with the single top level bar for now then add lower level level bars?
I will double check with statistical colleagues re 'percentage of indicators' approach but it makes sense to me as it asks for proportion of indicators that are fully disaggregated rather than an overall view of disaggregations.
Am thinking we also need a separate ticket to consider where/how we can see the specifics of what is disaggregated at the indicator level and this is where would see your scenario of things being almost fully disaagregated. For headline data we see the general overview on reporting status page but then on goal page we can see the specifics of which of the indicators has been reported. So for disaggregations where/how do we show what the target vs actual disaggregations are - somewhere on indicator page?

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin @AnnCorp  is there a way of seeing the above. I'm not sure I've been totally involved in this development to date and its tricky to provide comment without context - thanks

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp @phillipgardiner @jwestw I wasn't obvious to me how to work this into the reporting status page, so I've just started off with a completely bare-bones "Disaggregation status" page to get initial thoughts.

![screenshot-127 0 0 1_4000-2020 10 20-17_06_51](https://user-images.githubusercontent.com/1319083/96644163-abe37f00-12f6-11eb-858d-48ec9b8542e6.png)

**Comment by brockfanning** [comment]
Idea discussed: Move the "Overall" section into each of the tabs, and change the first tab to "Reporting status" instead of "Status by goal". Then disaggregation status could be additional tabs.

**Comment by brockfanning** [comment]
Along this lines of the above, here are some minimal screenshots of a rough draft:

![disagg-status-1](https://user-images.githubusercontent.com/1319083/97096435-423adc00-163a-11eb-95ea-a61431f175e4.png)

![disagg-status-2](https://user-images.githubusercontent.com/1319083/97096437-45ce6300-163a-11eb-974d-6ecd903e413a.png)

![disagg-status-3](https://user-images.githubusercontent.com/1319083/97096438-48c95380-163a-11eb-8eec-7b70facacb08.png)

![disagg-status-4](https://user-images.githubusercontent.com/1319083/97096441-4c5cda80-163a-11eb-9eeb-17b4c6b4a583.png)

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin Yeah that's pretty much how I saw it working out. The only thought in my mind is weather we introduce different bar chart colours for the dissagregation data to help differentiate them - but as an MVP probably not and its something I can access perhaps in the next round of usability testing.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw @AnnCorp @philipashlock This is ready now for a feature branch review. I added the technical details to #970.
