### ISSUE TITLE
Sorting of sub-categories and table headers

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#814]
The subcategories are sorted alphabetically by their translations. This sometimes causes a strange order in the selection options and table headers especially when they contain numerical values like here:

![grafik](https://user-images.githubusercontent.com/50657629/90392775-cba8bd80-e08f-11ea-9dca-67fe6a2beec7.png)

If I am not mistaken the sorting used to be on the basis of the values coming from the csv-files not on the translations. In this case it was possible to sort them by adding an a), b), c) at the beginning of the value.
Is there anything to be said against sorting again according to the values and not according to the translations?

**Comment by brockfanning** [comment]
@MoBosse To help me look for possible fixes, can you tell me which indicator your screenshot is from?

**Comment by brockfanning** [comment]
@MoBosse In the long term I think we may need to introduce the concept of a data schema to Open SDG, which would control the sorting order. I'm thinking now on how this would work, and I'll post again when I have some ideas.

In the short term, if you want to quickly revert to the old behavior, you could try removing the `languages` option in your [data configuration](https://github.com/G205SDGs/sdg-data/blob/develop/config_data.yml#L9). This `languages` option enables what we're calling "translated builds" - where the data/metadata is translated during the data build, and stored in subfolders (eg, `https://g205sdgs.github.io/sdg-data/de/data/11-4-1.csv`). If you remove turn off translated builds (by removing `languages` from your data config) then the subfolders are removed (eg, `https://g205sdgs.github.io/sdg-data/data/11-4-1.csv`).

The site (after it is rebuilt the next time) should be able to automatically recognize that translated builds are off and adjust all links. One note to keep in mind, with translated builds, the "Download source CSV" button produces translated CSV files. But with translated builds off, that button produces untranslated CSV files.

As you can gather from the description of the quick fix, the problem is that Open SDG sorts those things alphabetically, and with translated builds, they have already been translated before they get to Open SDG.

**Comment by LucyGwilliamAdmin** [comment]
### Is your feature request related to a problem? Please describe.

Go here: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/datapreview_Frensisbras-patch-13/17-18-1/
Expand the Goal dropdown
It's expected that the categories would go Goal 1, Goal 2, Goal 3, ..., Goal 17 but that is not the case.

Instead it goes Goal 1, Goal 10, Goal 11, Goal 12, ..., Goal 17, Goal 2, Goal 3, ..., Goal 9

Think this also an issue for other disaggregations e.g. Age

###Describe the solution that you need
Need to either be able to set the order or add in something about numeric ordering

### Why do you need this feature?
So that disaggregations that use numeric values appear in the expected order

### Describe alternatives you've considered
Considered adding A., B., C., before the values to ensure that they're in order but this can be quite messy and goes against standardised values so not really a good fix.

### Additional context
Add any other context or screenshots about the feature request here.
