### ISSUE TITLE
Ensure disabled components are clear to screen readers

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#850]
**Page 144 in DAC report**

**Issue from DAC report:**
Colour alone is used to indicate that the button is disabled. Low vision users reliant on alternative colour schemes could not identify why the button was not functioning.

Additionally, the mouse pointer changes to a hand which serves as a visual cue to low vision users to indicate this element is clickable.

**Solution from DAC report:**
Ensure that the mouse pointer does not change for disabled components.

```
CSS:
*[disabled], *[aria-disabled="true"] {
cursor: default;
}
```
Please consider including some text in the label to describe that a button is disabled.

**Example from DAC report:**

```
<button id="clear" aria-disabled="true" class="disabled">Clear selections (button disabled)<i class="fa fa-remove"></i></button>
```

![image](https://user-images.githubusercontent.com/43404358/91592330-4b6b3d80-e956-11ea-87a5-842357b633ab.png)

**Comment by brockfanning** [comment]
The mouse cursor fix is quite easy and is implemented in #876.

Regarding the additional text on the button, personally I would prefer to avoid that, for a couple of reasons:
1. It crowds the UI, especially on mobile
2. It would need to be translated

Since the disabled button is already pushing the boundaries of color contrast limits (I assume), I'd propose making the button always be enabled. As an alternative to having it disabled, if it is clicked while there are no selections, the user could get an alert (such as "Sub-category selections were already cleared."). This is in line with a sentiment I've seen online about [disabled buttons being bad](https://axesslab.com/disabled-buttons-suck/?utm_source=dlvr.it&).

But I can also go ahead with adding "button disabled" on the button if that is the decision.

I also considered proposing that it be hidden altogether when there are no selections, rather than disabled. But unfortunately this causes the checkboxes to jump up/down vertically, which hurts the UX.

**Comment by phillipgardiner** [comment]
@AnnCorp @brockfanning @jwestw Additional text on a button is not something I have heard of before for this. Looking at the way it is written too is that not just a consideration rather than a have to do? and I'm assuming this is for low vision issues rather than screen reader issues.

From a usability perspective I think part of the issue is it does not look like a button in the first place. Just the way it is styled and the fact it has an 'x' on it etc makes it seem different to a button (e.g. compare it to our green data download buttons). 

When disabling a button, one tendency used in design (instead of greying out) is to reduce the opacity of the colour. But in this instance it starts out white so its hard to reduce the opacity. We could look at making it more button like and changing its colour, then reducing the opacity when disabled?

Maybe a better option is to replace the button with a blue 'Clear all' link instead of a button, a bit like in this diagram 
![image](https://user-images.githubusercontent.com/60919820/92395939-14e2af00-f11c-11ea-8705-11d70db43f97.png) and have it greyout when disabled (as well as the already implemented mouse pointer change)

An alternate is to ask ourselves the question, what is the impact if it wasn't there at all? Would this impact user a lot given they can still clear each box individually, is 'clearing all' something they do alot? - I don't know the answer to this!

All just thoughts...

Ps I found this article which is an interesting read: https://a11y-101.com/development/aria-disabled

**Comment by phillipgardiner** [comment]
@brockfanning Hey. Been thinking about this a bit more. If we went down the route of displaying an error message, would those messages not have have be translated?

**Comment by brockfanning** [comment]
@phillipgardiner Yes, we'd need to translate that text.

Though that's not a dealbreaker. We've already added a few phrases as part of these accessibility fixes that will also need to be translated.

**Comment by phillipgardiner** [comment]
@brockfanning I wonder if doing something liek this would be sufficient for now?

<img width="572" alt="Screenshot 2020-09-09 at 13 05 10" src="https://user-images.githubusercontent.com/60919820/92596339-96ae1600-f29d-11ea-8482-b7f1dc38d47a.png">

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner @AnnCorp @jwestw reply from DAC:

- Text in label is not necessary
- This will be sufficient: use attribute `disabled="disabled"` when `aria-disabled="true"` so that fact button is disabled is reflected in Windows High Contrast Colour schemes, button wont receive keyboard focus and mouse pointer wont change by default:
<img width="199" alt="pic" src="https://user-images.githubusercontent.com/43404358/92737262-e3afec00-f372-11ea-9f7e-3f7815c3e3d7.png">

**Comment by jwestw** [comment]
Feature branch: sdgdev-813006012.eu-west-1.elb.amazonaws.com/jw-test-disabled-button-fixes

**Comment by jwestw** [comment]
I think I have just noticed a problem with this:
**MS Windows + MS Edge + Windows _High contrast_ mode**
(Note the y-axis units)
![image](https://user-images.githubusercontent.com/67740306/92912784-0d741c00-f422-11ea-938b-bd26e7115362.png)


Compare to:
**MS Windows + MS Edge + Windows normal mode**
(Note the y-axis units)
![image](https://user-images.githubusercontent.com/67740306/92912450-b706dd80-f421-11ea-9ae2-6fd51b8a6a09.png)
