### ISSUE TITLE
Use text symbol instead of image for sort arrows in table

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#854]
**Page 43 in DAC report**

**Issue from DAC report:**
Important information including symbols indicating functionality are implemented as background images within the CSS which disappear in Windows high contrast mode. The full screen and search icons do not invert colours in high contrast mode.

Note: this is not using Open SDG high-contrast mode but Windows high contrast mode, so to recreate, turn on High contrast mode in Windows settings and open page in Internet Explorer

**Solution from DAC report:**
Please use a text symbol inline rather than a background image within the CSS. This means that the colours can be set within the HTML to ensure that content does not disappear when alternative styles are applied.

![image](https://user-images.githubusercontent.com/43404358/91593225-ad787280-e957-11ea-855d-e97499bad95e.png)

**Comment by brockfanning** [comment]
This one might merit discussion with DAC. This is a very narrow audience: Windows users, using Windows high-contrast, in Internet Explorer. IE will be officially abandoned by Microsoft in less than a year. Do we want to spend the effort on such a narrow case?

Also we should consider Windows high-contrast mode in general? We have devoted considerable time to our own custom high-contrast mode. Is there any way we can focus on that development, rather than trying to support OS-specific high-contrast modes?

**Comment by jwestw** [comment]
Hi Brock - absolutely agree with you here. IE will soon be dropped. Edge will take over, which itself is based on Chromium base, so we shouldn't cater for IE. 

With regards to Windows high contrast mode I have no idea how widely used it is, so can't really comment here.  

Side note: When I used high contrast mode in Windows, Chrome offers the High Contrast Extension (by: chrome-a11y-extensions).

**Comment by LucyGwilliamAdmin** [comment]
Fix for this has been merged so I'll close it
