### ISSUE TITLE
Relay max chart lines warning to screen readers and make it clearer it's appeared

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#856]
Part of this relates to https://github.com/open-sdg/open-sdg/issues/163

**Page 70 in DAC report**

**Issue from DAC report:**
There is nothing to indicate to screen reader users that a warning has appeared on the page upon their selection. When users do encounter this by navigating through the page, there is nothing to indicate that it is a warning message as this is indicated visually via a yellow background and lightning bold icon with no text alternative. Low vision users also found it difficult to locate this message.

**Solution from DAC report:**
Adding a role of alert to the containing <div> will ensure this message is relayed to screen reader users when it appears onscreen as it will recognise that the CSS style ‘display:none;’ has changed to ‘display:block;’.

Additionally, please consider implementing the message in line with the sub-category components so that low vision users’ navigation with high page magnification may perceive that it has appeared.

**Example from DAC report:**

```
<div id="dataset-size-warning" style="" role="alert">
    <i class="fa fa-bolt"><span class="visuallyhidden">Warning:</span></i>
      There are too many dataset sub-categories specified to show on the chart.
      Not all will be shown until you remove some selections.
</div>
```

**Comment by brockfanning** [comment]
@AnnCorp @LucyGwilliamAdmin @jwestw @phillipgardiner I realized the reason that the too-many-datasets message is inside the chart tab: that limitation only applies to the chart. The table tab doesn't suffer from that limitation, because it can have any number of columns. So, if we move this message to the sidebar, it would be a bit awkward to explain that it only applies to the chart.

I can go ahead with everything except moving it, while we discuss.
