### ISSUE TITLE
Target lines

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#913]
**Is your feature request related to a problem? Please describe.**

The Open SDG platform shows the current status of the indicators, but not the progress towards the 2030 goal.

**Describe the solution that you need**

There needs to be some way to draw a "target line" on the charts, representing the 2030 goal for that indicator.

**Why do you need this feature?**

This is needed to allow Open SDG to show progress.

**Describe alternatives you've considered**

Possible more advanced functionality in the future may include year-by-year targets, but for now let's just get a straight line on chart representing the end (2030) goal.

**Comment by brockfanning** [comment]
@phillipgardiner @LucyGwilliamAdmin @jwestw @AnnCorp This appears to be easy to do, thanks to an open-source plugin for Chart.js called [chart-js-annotation](https://github.com/chartjs/chartjs-plugin-annotation). I've got a proof of concept up at #912. Here's a screenshot:

![screenshot-127 0 0 1_4000-2020 09 24-11_15_39](https://user-images.githubusercontent.com/1319083/94164913-9eea8180-fe57-11ea-9f98-9574ce44d100.png)
 
This is controlled by the countries with some simple code in the indicator metadata:

```
graph_annotations:
    - preset: target_line
      value: 1
```

So I think the remaining steps for this are:
1. Make all the visual decisions for the dashed line. Eg, what color should it be? How wide should the dashes be? How thick should the dashes be? Etc. (Realizing that countries can customize our defaults - we just need to decide on the defaults).
2. Decide how we should label it. Eg, should the label appear on the line? Outside the graph? In the legend? Also what should the label say?
3. Depending on what we decide for the label, we'll need to figure out how to convey the information to screenreaders.
4. Depending on what we decide for the label, we'll need to translate that label.

**Comment by phillipgardiner** [comment]
@phillipgardiner @LucyGwilliamAdmin @jwestw @AnnCorp happy to feed in thoughts when required.

**Comment by brockfanning** [comment]
@phillipgardiner Feel free to post any ideas. I was holding off on further development until we make these decisions.

**Comment by phillipgardiner** [comment]
@brockfanning In regards to points 1 and 2 its hard to write a precise answer as so much depends on the if and buts of what we do with the other lines (if anything) as ultimately it is important that we differentiate, and draw the users attention to where we need (e.g. we may consider using bright colours for the target line and UK line, but saturated colours for the other data sets. We may need to reconsider the use of dashed lines for data sets etc etc). I think this ticket will need to tie in with the one we have somewhere around chart colours (e.g. accessibility). Prob easier to discuss on a tech call.

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin @AnnCorp  much consideration on this, ultimately there is a lot of correct answers as you trade off one decision against the other. But I believe the default (given countries can change it themselves) should be:

-  a standard dashed line
- the width should be the same as the dissagregated lines displayed on the UK charts (sorry I don't know what the actual width being displayed is?)
- colour to be GOV UK dark grey #505a5f
- Ideally the label would appear next to the line (see example) but I'm not sure what effect this would have on the graph width and tabs etc
- The label would be called '2030 Target'

As discussed on the call this is just a default, which I would expect countries to change in order to work within the context of their own graphs. It would probably be best to implement this and then tweak if we believe any changes are required. Ultimately I already know the grey will clash with the primary line colour used on the UK website, but i believe this is because the primary line colour needs to change rather than the goals colour.

![image](https://user-images.githubusercontent.com/60919820/94695482-e11b3380-032d-11eb-9367-0b94f17c867f.png)
