### ISSUE TITLE
Key and map colours don't match in Windows High Contrast Mode

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#955]
![image](https://user-images.githubusercontent.com/43404358/95862337-ad430380-0d5a-11eb-9a03-04dae3d4280a.png)

**Comment by brockfanning** [comment]
A related note: I just opened up #956 which has a link to a recent blog post. I still need to try it out, but I'm hopeful that it will be a useful way to have our custom high-contrast mode also work in other high-contrast modes. I suspect that it will not work in IE, but according to that blog post it does work in Edge, so probably Chrome as well. More soon.

**Comment by brockfanning** [comment]
It turns out that we can use the approach in [that blog post](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/) to fix this issue in Edge and IE only. @LucyGwilliamAdmin Do you think this might be sufficient given that Edge and IE are popular with Windows users?
