### ISSUE TITLE
Moving to different automation service

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#978]
I don`t know if any other country uses travis-ci, but I noticed that my commits in travis-ci have been queuing for a very long time for a few days.
When I did a bit of research I found out that travis-ci **.org** will be shut down at the end of this year and that all repositories have to be moved to travis-ci **.com**

Could anyone provide some information on how to move to another automation service (not necessarily travis-ci.com)?

Thanks!

**Comment by LucyGwilliamAdmin** [comment]
Hi @MoBosse 

We in the UK (and also the Open SDG starter repos) have moved away from using Travis and Circle CI. We (and the starter repos by default) now use GitHub actions.

It was actually quite a straight forward process to move over as well.
Here are the files that are used in the data starter repo: https://github.com/open-sdg/open-sdg-data-starter/tree/develop/.github/workflows

And here are the files we use in the UK data repo: https://github.com/ONSdigital/sdg-data/tree/develop/.github/workflows - we added another workflow so that tests are also carried out on pushes

Similarly, here are the files that are used in the site starter repo: https://github.com/open-sdg/open-sdg-site-starter/tree/develop/.github/workflows

And the files that we use in the UK site repo: https://github.com/ONSdigital/sdg-indicators/tree/develop/.github/workflows - again we do have an extra file as we are exploring the use of automated accessibility testing

The use of keys here is much simpler - the within repo workflows use the built-in `secrets.GITHUB_TOKEN` and keys only need to be created for workflows that interact with different repos/orgs (so one per each staging repo).

Instructions to create secrets can be found in the docs here: https://open-sdg.readthedocs.io/en/latest/quick-start/#creating-an-access-token

**Comment by MoBosse** [comment]
Hi @LucyGwilliamAdmin 
thanks a lot. I'll give that a try and will give feedback if it foorks for me.

**Comment by MoBosse** [comment]
Hi @LucyGwilliamAdmin,
I had to add [scripts/test/html_proofer_staging.sh ](https://github.com/G205SDGs/sdg-indicators/blob/develop/scripts/test/html_proofer_staging.sh) as well and for some reason I had to change `gh-pages` to `master` [here](https://github.com/G205SDGs/sdg-data/blob/develop/.github/workflows/deploy-to-production.yml#L51) but now it works.
Thanks again for your help.
