### ISSUE TITLE
Search by indicator number not working in german

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#979]
**Please complete the following information** 
Site repository URL: https://github.com/G205SDGs/sdg-indicators
Open SDG version: 1.1.0

**Describe the bug**
The search of an indicator number ("1.1.1" nor "1-1-1") works when language "English" is selected but does not work for language "German".

**To Reproduce**
1. Go to 'http://sdg-indikatoren.de/'
2. Search for '1.1.1'
2.1 Result: 
![grafik](https://user-images.githubusercontent.com/50657629/98819607-5732b000-242d-11eb-8a84-e7e263f0166c.png)

3. Go to 'http://sdg-indicators.de/'
4. Search for '1.1.1'
4.1. Result: 
![grafik](https://user-images.githubusercontent.com/50657629/98819721-80ebd700-242d-11eb-8be7-25eb3d60dd21.png)

**Expected behavior**
The search should work in any language

**Additional context**
I don`t know if the search should work without but I added "indicator_number" to the "search_index_extra_fields"

**Comment by brockfanning** [comment]
@MoBosse For languages besides English we attempt to use the third-party library [lunr-languages](https://github.com/MihaiValentin/lunr-languages) with the assumption that it's beneficial to the search functionality. The lunr-languages project doesn't support all languages, but it does support German. However in this case it sounds like whatever that library is doing is preventing searching by indicator ids.

A quick fix would be to prevent lunr-languages from loading, which can be done by removing [these lines](https://github.com/open-sdg/open-sdg/blob/master/_layouts/search.html#L71-L74). But presumably that library is doing something useful, so that may not be the best solution.

An alternative might be to add some javascript that specifically recognizes indicator IDs and does something to ensure that they work. (I'm not sure offhand what that would be exactly but I suspect it's possible.)

Also to answer your question - no you should not need to add indicator_number in search_index_extra_fields. Indicator IDs should get added automatically (same with goal IDs).

**Comment by brockfanning** [comment]
@MoBosse This should be fixed by #1110 if you would like to test it out.

**Comment by MoBosse** [comment]
@brockfanning I was testing it [here](https://sdgtestenvironment.github.io/sdg-indicators/search/?q=6.1.1) but it seems not to work.
Did I do something wrong?

**Comment by brockfanning** [comment]
@MoBosse Instead of pointing to open-sdg/1.3.0-dev you should point to brockfanning/multilingual-indicator-id-search. Also you should delete your _includes/assets/js/search.js file. Everything looks good.

**Comment by MoBosse** [comment]
Thanks @brockfanning 
Now it works perfectly and finds Indicator IDs as expected!
[https://sdgtestenvironment.github.io/sdg-indicators/search/?q=1.1.1](https://sdgtestenvironment.github.io/sdg-indicators/search/?q=1.1.1)

**Comment by brockfanning** [comment]
Thanks for testing @MoBosse!
